USE WTS
GO

IF OBJECT_ID (N'dbo.Resource_HasDependencies', N'FN') IS NOT NULL
    DROP FUNCTION [dbo].[Resource_HasDependencies];
GO


CREATE FUNCTION [dbo].[Resource_HasDependencies]
(
	@UserId int
)
RETURNS bit
AS
BEGIN
	DECLARE @count int;
	SET @count = 0;

	
	SELECT @count = COUNT(WORKREQUESTID)
	FROM 
		WORKREQUEST WR
	WHERE
		WR.SMEID = @UserID
		OR WR.LEAD_IA_TWID = @UserID
		OR WR.LEAD_RESOURCEID = @UserID;
		
	IF ISNULL(@count,0) > 0
	BEGIN
		RETURN 1;
	END;

	SELECT @count = COUNT(WORKITEMID)
	FROM 
		WORKITEM WI
	WHERE
		WI.ASSIGNEDRESOURCEID = @UserID
		OR WI.PRIMARYRESOURCEID = @UserID
		OR WI.SECONDARYRESOURCEID = @UserID;

	IF ISNULL(@count,0) > 0
	BEGIN
		RETURN 1;
	END;
	
	--SELECT @count = COUNT(WORKITEM_UPDATEID)
	--FROM 
	--	WORKITEM_UPDATE WIU
	--WHERE
	--	WIU.ITEM_UPDATETYPEID = @UserID;

	IF ISNULL(@count,0) > 0
	BEGIN
		RETURN 1;
	END;
	
	SELECT @count = COUNT(WIT.WORKITEM_TASKID)
	FROM 
		WORKITEM_TASK WIT
		--, WORKITEM_TASK_UPDATE WITU
		, WORKITEM_SUBSCRIBER WIS
	WHERE
		WIT.ASSIGNEDRESOURCEID = @UserID
		--OR WITU.ITEM_UPDATETYPEID = @UserID
		OR WIS.WTS_RESOURCEID = @UserID;

	IF ISNULL(@count,0) > 0
	BEGIN
		RETURN 1;
	END;
	
	--SELECT @count = COUNT(WORKITEM_TASK_UPDATEID)
	--FROM 
	--	WORKITEM_TASK_UPDATE WITU
	--WHERE
	--	WITU.ITEM_UPDATETYPEID = @UserID;

	--IF ISNULL(@count,0) > 0
	--BEGIN
	--	RETURN 1;
	--END;
	
	SELECT @count = COUNT(WORKITEM_SUBSCRIBERID)
	FROM 
		WORKITEM_SUBSCRIBER WIS
	WHERE
		WIS.WTS_RESOURCEID = @UserID;

	IF ISNULL(@count,0) > 0
	BEGIN
		RETURN 1;
	END;

	SELECT @count = COUNT(1)
	FROM 
		WTS_SYSTEM WS
	WHERE
		WS.BusWorkloadManagerID = @UserID
		OR WS.DevWorkloadManagerID = @UserID;

	IF ISNULL(@count,0) > 0
	BEGIN
		RETURN 1;
	END;

	RETURN 0;
END;

GO
