USE WTS
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[ItemTypeList_Get]')
AND OBJECTPROPERTY(id, N'IsProcedure') = 1)

DROP PROCEDURE [ItemTypeList_Get]

GO

CREATE PROCEDURE [dbo].[ItemTypeList_Get]
AS
BEGIN
declare @IntakeTeamCount int = 0;
select @IntakeTeamCount = count(distinct wsr.WTS_RESOURCEID)
FROM WTS_SYSTEM_RESOURCE wsr
where wsr.ActionTeam = 1

SELECT 
	'' AS A
	,WORKITEMTYPE.WORKITEMTYPEID
	,WORKITEMTYPE AS 'Item Type'
	,DESCRIPTION AS 'Description'
	,WorkActivityGroupID
	,PDDTDR_PHASEID
	,WorkloadAllocationID
	,SORT_ORDER AS 'Sort Order'
	,ARCHIVE AS 'Archive'
	,ISNULL([Work Items], 0) AS 'Work Items'
	,ISNULL([Open Items],0) AS 'Open Items'
	,ISNULL([Closed Items],0) AS 'Closed Items'
	,ISNULL((SELECT COUNT(*) 
						FROM WORKITEMTYPE_Status WITS 	
						WHERE WITS.WORKITEMTYPEID = WORKITEMTYPE.WORKITEMTYPEID),0) AS 'Status_Count' 
	,ISNULL((SELECT COUNT(*) 
						FROM WorkActivity_WTS_RESOURCE_TYPE WAWRT	
						WHERE WAWRT.WORKITEMTYPEID = WORKITEMTYPE.WORKITEMTYPEID),0) AS 'Resource_Type_Count' 
	,ISNULL((SELECT COUNT(*) + @IntakeTeamCount 
						FROM WorkActivity_WTS_RESOURCE WAWR	
						WHERE WAWR.WORKITEMTYPEID = WORKITEMTYPE.WORKITEMTYPEID),0) AS 'Resource_Count' 
	,'' AS X
FROM WORKITEMTYPE
LEFT JOIN (
	SELECT DISTINCT a.WORKITEMTYPEID, SUM(a.[Work Items]) as [Work Items], SUM(a.[Open Items]) as [Open Items], SUM(a.[Closed Items]) as [Closed Items] FROM (
		SELECT WORKITEMTYPEID 
			,COUNT(*) AS 'Work Items'
			,SUM(CASE WHEN STATUS.STATUS IN ('New', 'In Progress', 'Info Provided', 'Un-Reproducible') THEN 1 ELSE 0 END) AS 'Open Items'
			,SUM(CASE WHEN STATUS.STATUS = 'Closed' THEN 1 ELSE 0 END) AS 'Closed Items'
		FROM WORKITEM 
		LEFT JOIN STATUS
		ON STATUS.STATUSID = WORKITEM.STATUSID
		GROUP BY WORKITEMTYPEID
	
		UNION 

		SELECT WORKITEMTYPEID 
			,COUNT(*) AS 'Work Items'
			,SUM(CASE WHEN STATUS.STATUS IN ('New', 'In Progress', 'Info Provided', 'Un-Reproducible') THEN 1 ELSE 0 END) AS 'Open Items'
			,SUM(CASE WHEN STATUS.STATUS = 'Closed' THEN 1 ELSE 0 END) AS 'Closed Items'
		FROM WORKITEM_TASK 
		LEFT JOIN STATUS
		ON STATUS.STATUSID = WORKITEM_TASK.STATUSID
		GROUP BY WORKITEM_TASK.WORKITEMTYPEID
	) as a
	GROUP BY a.WORKITEMTYPEID
) AS wi
ON wi.WORKITEMTYPEID = WORKITEMTYPE.WORKITEMTYPEID
ORDER BY [Sort Order]
END
