USE WTS
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[PDDTDR_Phase_Get]')
AND OBJECTPROPERTY(id, N'IsProcedure') = 1)

DROP PROCEDURE [PDDTDR_Phase_Get]

GO

CREATE PROCEDURE [dbo].[PDDTDR_Phase_Get]
	@PDDTDR_PhaseID int
AS
BEGIN
	SELECT
		p.PDDTDR_PhaseID
		, p.PDDTDR_Phase
		, p.[DESCRIPTION]
		, (SELECT COUNT(WORKITEMID) 
			FROM WORKITEM wi
				JOIN [STATUS] s ON wi.STATUSID = s.STATUSID
					JOIN STATUS_PHASE sp ON sp.STATUSID = s.STATUSID
			WHERE sp.PDDTDR_PHASEID = p.PDDTDR_PHASEID) AS WorkItem_Count
		, (SELECT COUNT(*) FROM STATUS_PHASE sp WHERE sp.PDDTDR_PhaseID = p.PDDTDR_PhaseID) AS Status_Count
		, p.SORT_ORDER
		, p.ARCHIVE
		, '' as X
		, p.CREATEDBY
		, p.CREATEDDATE
		, p.UPDATEDBY
		, p.UPDATEDDATE
	FROM
		PDDTDR_Phase p
	WHERE
		p.PDDTDR_PhaseID = @PDDTDR_PhaseID;

END;

GO
