USE [WTS]
GO

/****** Object:  StoredProcedure [dbo].[RQMTSet_Task_Delete]    Script Date: 9/27/2018 2:17:12 PM ******/
DROP PROCEDURE [dbo].[RQMTSet_Task_Delete]
GO

/****** Object:  StoredProcedure [dbo].[RQMTSet_Task_Delete]    Script Date: 9/27/2018 2:17:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[RQMTSet_Task_Delete]
(
	@RQMTSetID INT,
	@RQMTSetTaskID INT,
	@DeletedBy NVARCHAR(255)
)
AS
BEGIN
	DECLARE @now DATETIME = GETDATE()
	DECLARE @WORKITEM_TASKID INT = (SELECT WORKITEM_TASKID FROM RQMTSet_Task WHERE RQMTSetTaskID = @RQMTSetTaskID)

	DELETE FROM RQMTSet_Task WHERE RQMTSetTaskID = @RQMTSetTaskID	
	
	DECLARE @WORKITEMID INT
	DECLARE @TASKNUMBER INT
	SELECT @WORKITEMID = WORKITEMID, @TASKNUMBER = TASK_NUMBER FROM WORKITEM_TASK WHERE WORKITEM_TASKID = @WORKITEM_TASKID

	DECLARE @AuditDesc NVARCHAR(100) = 'TASK ' + CONVERT(VARCHAR(100), @WORKITEMID) + '-' + CONVERT(VARCHAR(100), @TASKNUMBER) + ' DELETED'

	EXEC dbo.AuditLog_Save @WORKITEM_TASKID, @RQMTSetID, 2, 6, 'TASK', NULL, @AuditDesc, @now, @DeletedBy


END
GO


