USE [WTS]
GO
/****** Object:  StoredProcedure [dbo].[SR_List_GetAll]    Script Date: 11/18/2016 2:04:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SR_List_GetAll]

AS
BEGIN

	SELECT CONVERT(nvarchar(10),  WT.WORKITEMID )+ ' - ' +  CONVERT(nvarchar(10), WT.TASK_NUMBER) AS ID
		, s.[STATUS] AS "Status"
		, CONVERT(nvarchar(10), WT.SRNUMBER) AS 'SR Number'
		, AR.FIRST_NAME + ' ' + AR.LAST_NAME AS 'Assigned To'
	FROM WORKITEM_TASK WT
	JOIN [STATUS] S ON WT.STATUSID = S.STATUSID
	LEFT JOIN WTS_RESOURCE AR ON WT.ASSIGNEDRESOURCEID = AR.WTS_RESOURCEID
	JOIN WORKITEM WI
	ON WT.WORKITEMID = WI.WORKITEMID
	WHERE SRNUMBER <> 0 AND SRNumber IS NOT NULL
	AND WI.WTS_SYSTEMID != 31 --WTS
UNION
	SELECT CONVERT(nvarchar(10),  WT.WORKITEMID )AS ID
		, s.[STATUS] AS "Status"
		, CONVERT(nvarchar(10), WT.SR_NUMBER) AS 'SR Number'
		, AR.FIRST_NAME + ' ' + AR.LAST_NAME AS 'Assigned To'
	FROM WORKITEM WT
	JOIN [STATUS] S ON WT.STATUSID = S.STATUSID
	LEFT JOIN WTS_RESOURCE AR ON WT.ASSIGNEDRESOURCEID = AR.WTS_RESOURCEID
	WHERE SR_NUMBER <> 0  AND SR_Number IS NOT NULL
	AND WT.WTS_SYSTEMID != 31 --WTS
	ORDER BY 'SR Number' DESC
	;

END
