
USE WTS
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[SR_WorkItemList_Get]')
AND OBJECTPROPERTY(id, N'IsProcedure') = 1)

DROP PROCEDURE [SR_WorkItemList_Get]

GO
USE [WTS]
GO
/****** Object:  StoredProcedure [dbo].[SR_WorkItemList_Get]    Script Date: 6/9/2016 2:51:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SR_WorkItemList_Get]
	@ShowArchived bit = 0
AS
BEGIN
	SELECT
		WI.WORKREQUESTID
		, WR.TITLE AS WORKREQUEST
		, WI.PDDTDR_PHASEID AS PhaseID
		, pp.PDDTDR_PHASE AS Phase
		, WI.WORKITEMID AS ItemID
		, WI.WORKITEMTYPEID
		, wit.WORKITEMTYPE
		, WI.WTS_SYSTEMID
		, WS.WTS_SYSTEM AS Websystem
		, WI.Production AS Production
		, wi.ProductVersionID
		, pv.ProductVersion AS [Version]
		, wi.STATUSID
		, s.[STATUS]
		, WI.TITLE
		, WI.[DESCRIPTION]
		, wi.PRIORITYID
		, P.[PRIORITY]
		, wr.SMEID
		, PA.FIRST_NAME + ' ' + PA.LAST_NAME AS Primary_Analyst
		, wi.PRIMARYRESOURCEID
		, PD.FIRST_NAME + ' ' + PD.LAST_NAME AS Primary_Developer
		, wi.ASSIGNEDRESOURCEID
		, AR.FIRST_NAME + ' ' + AR.LAST_NAME AS Assigned
		, wi.CREATEDBY
		, WI.CREATEDDATE AS CREATEDDATE
		, wi.SubmittedByID
		, SR.FIRST_NAME + ' ' + SR.LAST_NAME AS SubmittedBy
		, WI.COMPLETIONPERCENT AS ProgressFROM
	FROM
		WORKITEM WI
			LEFT JOIN WORKREQUEST WR ON WI.WORKREQUESTID = WR.WORKREQUESTID
				LEFT JOIN PDDTDR_PHASE pp ON WI.PDDTDR_PHASEID = pp.PDDTDR_PHASEID
				LEFT JOIN WTS_RESOURCE PA ON WR.SMEID = PA.WTS_RESOURCEID
			LEFT JOIN WORKITEMTYPE wit ON WI.WORKITEMTYPEID = wit.WORKITEMTYPEID
			JOIN WTS_SYSTEM WS ON WI.WTS_SYSTEMID = WS.WTS_SYSTEMID
			LEFT JOIN ProductVersion pv ON WI.ProductVersionID = pv.ProductVersionID
			JOIN [PRIORITY] P ON WI.PRIORITYID = P.PRIORITYID
			LEFT JOIN WTS_RESOURCE SR ON WI.SubmittedByID = SR.WTS_RESOURCEID
			LEFT JOIN WTS_RESOURCE AR ON WI.ASSIGNEDRESOURCEID = AR.WTS_RESOURCEID
			JOIN [STATUS] S ON WI.STATUSID = S.STATUSID
			LEFT JOIN WTS_RESOURCE PD ON WI.PRIMARYRESOURCEID = PD.WTS_RESOURCEID
	WHERE
		wit.WORKITEMTYPE LIKE 'Sustainment%'
		AND CASE WHEN @ShowArchived = 1 THEN 0 ELSE WI.Archive END = 0
	ORDER BY UPPER(WI.TITLE);

END;

