USE WTS
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[SRView_Get]')
AND OBJECTPROPERTY(id, N'IsProcedure') = 1)

DROP PROCEDURE [SRView_Get]

GO
USE [WTS]
GO
/****** Object:  StoredProcedure [dbo].[SRView_Get]    Script Date: 12/1/2016 2:48:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SRView_Get]
	 
	 @ShowArchived BIT = 0
	,@ShowClosed BIT = 0
	,@ShowBacklog BIT = 0
	,@OwnedBy int = null

AS
BEGIN

	SELECT  
		wtss.WTS_SYSTEM AS 'Websystem'
		, p.PRIORITY AS 'Priority'
		, CONVERT(nvarchar(10),  WT.WORKITEMID )AS 'ItemID'
		, 0 AS 'SubTaskID'
		, wt.SR_Number as 'SR_Number'
		, PB.FIRST_NAME + ' ' + PB.LAST_NAME AS 'Primary Bus. Res.'
		, PT.FIRST_NAME + ' ' + PT.LAST_NAME AS 'Primary Tech. Res.'
		, s.[STATUS] AS 'Status'
		, WT.COMPLETIONPERCENT AS '% Complete'
		, WT.TITLE AS 'Title'
		, WT.DESCRIPTION AS 'Description'
		, ' ' AS 'Sub Task Title'
		, WT.CREATEDBY + ' ' + CAST(WT.CREATEDDATE AS VARCHAR(20)) AS 'Created'
		, WT.UPDATEDDATE AS 'Last Updated'
		,
		CASE 
		WHEN WT.STATUSID IN (9, 10, 15, 70)
		THEN
			IsnULL(DATEDIFF(d, (SELECT MIN(UPDATEDDATE) FROM WorkItem_History 
			WHERE WORKITEMID = WT.WORKITEMID AND ITEM_UPDATETYPEID = 5), 
			(SELECT MAX(UPDATEDDATE) FROM WorkItem_History 
			WHERE WORKITEMID = WT.WORKITEMID 
			AND ITEM_UPDATETYPEID = 5 
			AND UPPER(FieldChanged) = 'STATUS' 
			AND UPPER(NewValue) in ('CLOSED'))), 0)
		ELSE
			IsnULL(DATEDIFF(d, (SELECT MIN(UPDATEDDATE) FROM WorkItem_History 
			WHERE WORKITEMID = WT.WORKITEMID AND ITEM_UPDATETYPEID = 5), GETDATE()), 0)
		END  AS 'Days Open'

		, WT.STATUSID
	FROM WORKITEM WT
	JOIN [STATUS] S ON WT.STATUSID = S.STATUSID
	JOIN WTS_SYSTEM wtss ON wtss.WTS_SYSTEMID = WT.WTS_SYSTEMID
	JOIN Priority p ON p.PRIORITYID = WT.PRIORITYID
	LEFT JOIN WTS_RESOURCE PB ON WT.PrimaryBusinessResourceID = PB.WTS_RESOURCEID
	LEFT JOIN WTS_RESOURCE PT ON WT.PRIMARYRESOURCEID = PT.WTS_RESOURCEID
	JOIN ProductVersion pv ON pv.ProductVersionID = WT.ProductVersionID
	WHERE SR_NUMBER <> 0  AND SR_Number IS NOT NULL 

UNION

	SELECT
		wtss.WTS_SYSTEM AS 'Websystem'
		, p.PRIORITY AS 'Priority'
		, CONVERT(nvarchar(10),  WT.WORKITEMID )AS 'ItemID'
		, wit.TASK_NUMBER AS 'SubTaskID'
		, wit.SRNUMBER as 'SR_Number'
		, PB.FIRST_NAME + ' ' + PB.LAST_NAME AS 'Primary Bus. Res.'
		, PT.FIRST_NAME + ' ' + PT.LAST_NAME AS 'Primary Tech. Res.'
		, s.[STATUS] AS 'Status'
		, WT.COMPLETIONPERCENT AS '% Complete'
		, WT.TITLE AS 'Title'
		, WT.DESCRIPTION AS 'Description'
		, wit.TITLE AS 'Sub Task Title'
		, WT.CREATEDBY + ' ' + CAST(WT.CREATEDDATE AS VARCHAR(20)) AS 'Created'
		, WT.UPDATEDDATE AS 'Last Updated'
		,
		CASE 
		WHEN WT.STATUSID IN (9, 10, 15, 70)
		THEN
			IsnULL(DATEDIFF(d, (SELECT MIN(UPDATEDDATE) FROM WorkItem_History 
			WHERE WORKITEMID = WT.WORKITEMID AND ITEM_UPDATETYPEID = 5), 
			(SELECT MAX(UPDATEDDATE) FROM WorkItem_History 
			WHERE WORKITEMID = WT.WORKITEMID 
			AND ITEM_UPDATETYPEID = 5 
			AND UPPER(FieldChanged) = 'STATUS' 
			AND UPPER(NewValue) in ('CLOSED'))), 0)
		ELSE
			IsnULL(DATEDIFF(d, (SELECT MIN(UPDATEDDATE) FROM WorkItem_History 
			WHERE WORKITEMID = WT.WORKITEMID AND ITEM_UPDATETYPEID = 5), GETDATE()), 0)
		END  AS 'Days Open'

		, WT.STATUSID
	FROM WORKITEM WT
	JOIN WORKITEM_TASK wit ON wit.WORKITEMID = WT.WORKITEMID
	JOIN [STATUS] S ON WT.STATUSID = S.STATUSID
	JOIN WTS_SYSTEM wtss ON wtss.WTS_SYSTEMID = WT.WTS_SYSTEMID
	JOIN Priority p ON p.PRIORITYID = WT.PRIORITYID
	LEFT JOIN WTS_RESOURCE PB ON WT.PrimaryBusinessResourceID = PB.WTS_RESOURCEID
	LEFT JOIN WTS_RESOURCE PT ON WT.PRIMARYRESOURCEID = PT.WTS_RESOURCEID
	JOIN ProductVersion pv ON pv.ProductVersionID = WT.ProductVersionID
	WHERE wit.SRNUMBER <> 0  AND wit.SRNumber IS NOT NULL 


	ORDER BY SR_Number;

END;

