USE WTS
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[THEMELIST_GET]')
AND OBJECTPROPERTY(id, N'IsProcedure') = 1)

DROP PROCEDURE [THEMELIST_GET]

GO

CREATE PROCEDURE [dbo].[THEMELIST_GET]
	@IncludeArchive INT = 0
AS
BEGIN
	SELECT
		t.THEMEID
		, t.THEME
		, t.DESCRIPTION
		, t.ARCHIVE
		, t.UPDATEDBY
		, t.UPDATEDDATE
	FROM
		THEME t
	WHERE 
		(@IncludeArchive = 1 OR t.Archive = 0)
	ORDER BY t.THEME ASC;
END;

GO
