USE [WTS]
GO
/****** Object:  StoredProcedure [dbo].[WORKREQUESTLIST_GET]    Script Date: 3/7/2017 3:16:41 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[WORKREQUESTLIST_GET]
	@SessionID nvarchar(100)
	, @UserName nvarchar(100)
	, @FilterTypeID int
	, @TypeID int = null
	, @RequestGroupID int = null
	, @ShowArchived BIT = 0
	, @OwnedBy int = null
AS
BEGIN
	WITH 
	 w_WI_UserFilter
	AS
	(
		SELECT FilterID, FilterTypeID
		FROM
			User_Filter uf
		WHERE
			uf.SessionID = @SessionID
			AND uf.UserName = @UserName
			AND uf.FilterTypeID IN (1,4)
	)
	, w_Filtered_WI
	AS
	(
		SELECT DISTINCT wit.WORKITEMID, wi.WORKREQUESTID
		FROM
			WORKITEM_TASK wit
			JOIN WORKITEM wi ON wi.WORKITEMID = wit.WORKITEMID
			JOIN w_WI_UserFilter wif ON wit.WORKITEM_TASKID = wif.FilterID AND FilterTypeID = 4
		WHERE
			(ISNULL(@OwnedBy,0) = 0 OR wit.ASSIGNEDRESOURCEID = @OwnedBy)
			OR (ISNULL(@OwnedBy,0) = 0 OR wit.PRIMARYRESOURCEID =  @OwnedBy)
			OR (ISNULL(@OwnedBy,0) = 0 OR wit.PRIMARYBUSRESOURCEID =  @OwnedBy)
			OR (ISNULL(@OwnedBy,0) = 0 OR wit.SECONDARYBUSRESOURCEID =  @OwnedBy)
		UNION
		SELECT 
			wi.WORKITEMID, wi.WORKREQUESTID
		FROM
			WORKITEM wi
				LEFT JOIN WORKREQUEST wr ON wi.WORKREQUESTID = wr.WORKREQUESTID
				JOIN w_WI_UserFilter wif ON wi.WORKITEMID = wif.FilterID AND FilterTypeID = 1
		WHERE
--			(ISNULL(@OwnedBy,0) = 0 OR wi.SubmittedByID = @OwnedBy) OR
			(ISNULL(@OwnedBy,0) = 0 OR wi.ASSIGNEDRESOURCEID = @OwnedBy)
			OR (ISNULL(@OwnedBy,0) = 0 OR wi.PRIMARYRESOURCEID =  @OwnedBy)
			OR (ISNULL(@OwnedBy,0) = 0 OR wi.SECONDARYRESOURCEID =  @OwnedBy)
			OR (ISNULL(@OwnedBy,0) = 0 OR wi.PrimaryBusinessResourceID =  @OwnedBy)
			--OR (ISNULL(@OwnedBy,0) = 0 OR wr.SMEID =  @OwnedBy)
			--OR (ISNULL(@OwnedBy,0) = 0 OR wr.LEAD_RESOURCEID =  @OwnedBy)
			--OR (ISNULL(@OwnedBy,0) = 0 OR wr.LEAD_IA_TWID =  @OwnedBy)
			--OR (ISNULL(@OwnedBy,0) = 0 OR wr.SUBMITTEDBY =  @OwnedBy)
			--OR (wi.WORKITEMID IN (SELECT WORKITEMID FROM w_OwnedTasks))
	)
	, w_Filtered
	AS
	(
		SELECT
			wr.*
		FROM
			WORKREQUEST wr
				LEFT JOIN w_Filtered_WI wi ON wr.WORKREQUESTID = wi.WORKREQUESTID
		WHERE
			(ISNULL(@OwnedBy,0) = 0 OR wr.SMEID =  @OwnedBy)
			OR (ISNULL(@OwnedBy,0) = 0 OR wr.LEAD_RESOURCEID =  @OwnedBy)
			OR (ISNULL(@OwnedBy,0) = 0 OR wr.LEAD_IA_TWID =  @OwnedBy)
			OR (ISNULL(@OwnedBy,0) = 0 OR wr.SUBMITTEDBY =  @OwnedBy)

			-- 12848 - 24 Added 4-11-2017:
			AND wr.Archive = 0
	) 
	SELECT DISTINCT
		'' AS X
		, WR.WORKREQUESTID
		, WR.RequestGroupID
		, rg.RequestGroup
		, WR.CONTRACTID
		, C.[CONTRACT]
		, WR.ORGANIZATIONID
		, O.ORGANIZATION
		, WR.REQUESTTYPEID
		, RT.REQUESTTYPE AS Request_Type
		, WR.WTS_SCOPEID
		, WS.[SCOPE] AS Work_Scope
		, WR.EFFORTID
		, E.EFFORT
		, WR.TITLE
		, WR.[DESCRIPTION]
		, (SELECT COUNT(*) FROM WORKREQUEST_SR WR_SR WHERE WR_SR.WORKREQUESTID = WR.WORKREQUESTID) AS SR_Count
		, (SELECT MAX(sr.CREATEDDATE) FROM WORKREQUEST_SR sr WHERE sr.WORKREQUESTID = WR.WORKREQUESTID) AS SR_Date
		, (SELECT COUNT(*) FROM WORKITEM WI WHERE WI.WORKREQUESTID = WR.WORKREQUESTID) AS WorkItem_Count
		, (SELECT MAX(wi.CREATEDDATE) FROM WORKITEM wi WHERE wi.WORKREQUESTID = WR.WORKREQUESTID) AS WorkItem_Date
		, WR.OP_PRIORITYID
		, P.[PRIORITY]
		, WR.SMEID
		, SME.FIRST_NAME + ' ' + SME.LAST_NAME AS SME
		, WR.LEAD_IA_TWID
		, LTW.FIRST_NAME + ' ' + LTW.LAST_NAME AS Lead_Tech_Writer
		, WR.LEAD_RESOURCEID
		, LR.FIRST_NAME + ' ' + LR.LAST_NAME AS Lead_Resource
		, '' AS My_Role
		, WR.SUBMITTEDBY
		, SB.FIRST_NAME + ' ' + SB.LAST_NAME AS Submitted_By
		, WR.ARCHIVE
	FROM
		w_Filtered WR
			JOIN REQUESTTYPE RT ON WR.REQUESTTYPEID = RT.REQUESTTYPEID
			LEFT JOIN RequestGroup rg ON WR.RequestGroupID = rg.RequestGroupID
			LEFT JOIN [CONTRACT] C ON WR.CONTRACTID = C.CONTRACTID
			LEFT JOIN ORGANIZATION O ON WR.ORGANIZATIONID = O.ORGANIZATIONID
			LEFT JOIN WTS_SCOPE WS ON WR.WTS_SCOPEID = WS.WTS_SCOPEID
			LEFT JOIN EFFORT E ON WR.EFFORTID = E.EFFORTID
			LEFT JOIN [PRIORITY] P ON WR.OP_PRIORITYID = P.PRIORITYID
			LEFT JOIN WTS_RESOURCE SME ON WR.SMEID = SME.WTS_RESOURCEID
			LEFT JOIN WTS_RESOURCE LTW ON WR.LEAD_IA_TWID = LTW.WTS_RESOURCEID
			LEFT JOIN WTS_RESOURCE LR ON WR.LEAD_RESOURCEID = LR.WTS_RESOURCEID
			LEFT JOIN WTS_RESOURCE SB ON WR.SUBMITTEDBY = SB.WTS_RESOURCEID
			LEFT JOIN WORKITEM wi ON WR.WORKREQUESTID = wi.WORKREQUESTID
	WHERE
		(ISNULL(@TypeID,0) = 0 OR WR.REQUESTTYPEID = @TypeID)
		AND (ISNULL(@RequestGroupID,0) = 0 OR WR.RequestGroupID = @RequestGroupID)
		AND CASE WHEN @ShowArchived = 1 THEN 0 ELSE WR.Archive END = 0
		AND CASE WHEN @ShowArchived = 1 THEN 0 ELSE WI.Archive END = 0

		-- 12848 - 24 Added 4-11-2017: 
		AND wi.STATUSID NOT IN (10, 70)
	ORDER BY
		--SR_Date DESC, WorkItem_Date DESC, WR.WORKREQUESTID DESC  -- Per 12848 -  24
		WR.WORKREQUESTID DESC
	;
	
	
END;

