USE WTS
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[WTS_SYSTEM_SUITE_DELETE]')
AND OBJECTPROPERTY(id, N'IsProcedure') = 1)

DROP PROCEDURE [WTS_SYSTEM_SUITE_DELETE]

GO

CREATE PROCEDURE [dbo].[WTS_SYSTEM_SUITE_DELETE]
	@WTS_SYSTEM_SUITEID int, 
	@exists bit output,
	@hasDependencies bit output,
	@deleted bit output,
	@archived bit output
AS
BEGIN
	SET @exists = 0;
	SET @hasDependencies = 0;
	SET @deleted = 0;
	SET @archived = 0;

	SELECT @exists = COUNT(WTS_SYSTEM_SUITEID)
	FROM WTS_SYSTEM_SUITE
	WHERE 
		WTS_SYSTEM_SUITEID = @WTS_SYSTEM_SUITEID;

	IF ISNULL(@exists,0) = 0
		RETURN;

	SELECT @hasDependencies = COUNT(*) FROM WTS_SYSTEM WHERE WTS_SYSTEM_SUITEID = @WTS_SYSTEM_SUITEID;

	IF ISNULL(@hasDependencies,0) > 0
		BEGIN
			--archive the user instead
			UPDATE WTS_SYSTEM_SUITE
			SET ARCHIVE = 1
			WHERE
				WTS_SYSTEM_SUITEID = @WTS_SYSTEM_SUITEID
			SET @archived = 1;
			RETURN;
		END;

	BEGIN TRY
		DELETE FROM WTS_SYSTEM_SUITE
		WHERE
			WTS_SYSTEM_SUITEID = @WTS_SYSTEM_SUITEID
		SET @deleted = 1;
	END TRY
	BEGIN CATCH
		SET @deleted = 0;
	END CATCH;
END;

