USE WTS
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[WTS_System_Suite_Resource_Delete]')
AND OBJECTPROPERTY(id, N'IsProcedure') = 1)

DROP PROCEDURE WTS_System_Suite_Resource_Delete
GO

CREATE PROCEDURE [dbo].[WTS_System_Suite_Resource_Delete]
	@WTS_SYSTEM_SUITE_RESOURCEID int, 
	@exists int output,
	@deleted int output
AS
BEGIN
	SET @exists = 0;
	SET @deleted = 0;

	SELECT @exists = COUNT(WTS_SYSTEM_SUITE_RESOURCEID)
	FROM WTS_SYSTEM_SUITE_RESOURCE
	WHERE 
		WTS_SYSTEM_SUITE_RESOURCEID = @WTS_SYSTEM_SUITE_RESOURCEID;

	IF ISNULL(@exists,0) = 0
		RETURN;

	BEGIN TRY
		DELETE FROM WTS_SYSTEM_SUITE_RESOURCE
		WHERE
			WTS_SYSTEM_SUITE_RESOURCEID = @WTS_SYSTEM_SUITE_RESOURCEID;

		SET @deleted = 1;
	END TRY
	BEGIN CATCH
		SET @deleted = 0;
	END CATCH;
END;

