ALTER TABLE RequestGroup
ALTER COLUMN [Description] nvarchar(4000) null;

GO

ALTER TABLE WORKREQUEST
ALTER COLUMN [DESCRIPTION] nvarchar(4000) null;

GO

ALTER TABLE WORKITEM
ALTER COLUMN [DESCRIPTION] nvarchar(4000) null;

GO

ALTER TABLE WORKITEM_TASK
ALTER COLUMN [DESCRIPTION] nvarchar(4000) null;

GO
