DECLARE @WTSID int
DECLARE @RESOURCEID int
DECLARE @WORKITEMTYPEID int
DECLARE @STATUSID int
DECLARE myCursor CURSOR FOR


SELECT WORKITEMID
FROM [WTS].[dbo].[WORKITEM]
WHERE WTS_SYSTEMID = 18 OR WTS_SYSTEMID = 31

OPEN myCursor

FETCH NEXT FROM myCursor
INTO @WTSID

WHILE @@FETCH_STATUS = 0

BEGIN
--UPDATE CHILD RECORDS
--Decromenting all ranks by 1
UPDATE [WTS].[dbo].[WORKITEM_TASK]
SET SORT_ORDER = SORT_ORDER + 1, BusinessRank = BusinessRank + 1
WHERE WORKITEMID = @WTSID;

FETCH NEXT FROM myCursor

INTO @WTSID

END

DEALLOCATE myCursor


--UPDATE PARENT RECORDS
--Decromenting all ranks by 1
UPDATE [WTS].[dbo].[WORKITEM]
SET RESOURCEPRIORITYRANK = RESOURCEPRIORITYRANK + 1, PrimaryBusinessRank = PrimaryBusinessRank + 1
WHERE WTS_SYSTEMID = 18 OR WTS_SYSTEMID = 31


BEGIN
	IF NOT EXISTS (SELECT * FROM [WTS].[dbo].[WorkType]
					WHERE [WorkType] = 'Plan/Test')
	BEGIN
		--INSERTING NEW RECORD INTO WorkType 
		--Plan/Test
		INSERT INTO [WTS].[dbo].[WorkType]
		VALUES ('Plan/Test', 'Business team activites', 2, 0, 'WTS_ADMIN', GETDATE(), 'WTS_ADMIN', GETDATE());
	END
END

SELECT @WORKITEMTYPEID = WorkTypeID
FROM [WTS].[dbo].[WorkType]
WHERE WorkType = 'Plan/Test';

BEGIN
	IF NOT EXISTS (SELECT * FROM [WTS].[dbo].[WorkType_PHASE]
					WHERE [WorkTypeID] = @WORKITEMTYPEID AND PDDTDR_PHASEID = 4 AND DESCRIPTION = 'Plan/Test work items(for Bussiness, Plan and Testing Phases)') --PDDTDR_PHASEID 4 = Develop Phase
	BEGIN
		--INSERTING NEW RECORD INTO WorkType 
		--PDDTDR_PHASEID has to be 4 or item won't appear in ddl. C# filtering based off 4
		INSERT INTO [WTS].[dbo].[WorkType_PHASE]
		VALUES (@WORKITEMTYPEID, 4, 'Plan/Test work items(for Bussiness, Plan and Testing Phases)', 2, 0, 'WTS_ADMIN', GETDATE(), 'WTS_ADMIN', GETDATE());
	END
END

DECLARE myCursor1 CURSOR FOR

SELECT WTS_RESOURCEID
FROM [WTS].[dbo].[WTS_RESOURCE]
WHERE ORGANIZATIONID = 3

OPEN myCursor1

FETCH NEXT FROM myCursor1
INTO @RESOURCEID

WHILE @@FETCH_STATUS = 0

BEGIN

--UPDATE PARENT RECORD
--Any WTS assigned to business team member that currently 'Build/Test' sets to 'Plan/Test'
UPDATE [WTS].[dbo].[WORKITEM]
SET WorkTypeID = @WORKITEMTYPEID
WHERE WorkTypeID = 3 AND ASSIGNEDRESOURCEID = @RESOURCEID AND WTS_SYSTEMID = 31;

FETCH NEXT FROM myCursor1

INTO @RESOURCEID

END

DEALLOCATE myCursor1


--CREATE RECORD IN STATUS FOR 'TEST/PLAN' TO POPULATE WHEN CHANGED TOO.
DECLARE myCursor2 CURSOR FOR
SELECT STATUSID 
FROM [WTS].[dbo].[STATUS_WorkType]
WHERE WorkTypeID = 3

OPEN myCursor2

FETCH NEXT FROM myCursor2
INTO @STATUSID

WHILE @@FETCH_STATUS = 0

BEGIN

BEGIN
	IF NOT EXISTS (SELECT * FROM [WTS].[dbo].[STATUS_WorkType]
				WHERE STATUSID = @STATUSID AND WorkTypeID = @WORKITEMTYPEID )
	BEGIN
	--INSERTING NEW RECORD INTO STATUS_WorkType 
	INSERT INTO [WTS].[dbo].[STATUS_WorkType]
	VALUES (@STATUSID, @WORKITEMTYPEID, NULL, 99, 0, 'WTS_ADMIN', GETDATE(), 'WTS_ADMIN', GETDATE());
	END
END


FETCH NEXT FROM myCursor2
INTO @STATUSID
END
DEALLOCATE myCursor2
