USE WTS
GO

ALTER TABLE WORKITEM
ADD SubmittedByID INT NULL;

GO

ALTER TABLE WORKITEM
ADD CONSTRAINT [FK_WORKITEM_WTS_RESOURCE] FOREIGN KEY ([SubmittedByID]) REFERENCES [WTS_RESOURCE]([WTS_RESOURCEID]);

GO

