USE WTS
GO

--DELETE FROM [ITEM_UPDATETYPE]
--GO

INSERT INTO [ITEM_UPDATETYPE](ITEM_UPDATETYPE, [DESCRIPTION], SORT_ORDER)
SELECT 'Delete', 'Item was deleted', (SELECT MAX(SORT_ORDER) + 1 FROM ITEM_UPDATETYPE)
EXCEPT
SELECT ITEM_UPDATETYPE, [DESCRIPTION], SORT_ORDER FROM ITEM_UPDATETYPE
GO

