ALTER TABLE RequestGroup
ALTER COLUMN [Description] nvarchar(max) null;

GO

ALTER TABLE WORKREQUEST
ALTER COLUMN [DESCRIPTION] nvarchar(max) null;

GO

ALTER TABLE WORKREQUEST
ALTER COLUMN JUSTIFICATION nvarchar(max) null;

GO

ALTER TABLE WORKITEM
ALTER COLUMN [DESCRIPTION] nvarchar(max) null;

GO

ALTER TABLE WORKITEM_TASK
ALTER COLUMN [DESCRIPTION] nvarchar(max) null;

GO
