USE WTS
GO

ALTER TABLE WORKITEM_TASK
ADD SubmittedByID int NULL;

GO

ALTER TABLE WORKITEM_TASK
ADD CONSTRAINT [FK_WORKITEM_TASK_SubmittedResource] FOREIGN KEY ([SubmittedByID]) REFERENCES [WTS_RESOURCE]([WTS_RESOURCEID]);

GO

ALTER TABLE WORKITEM_TASK
ADD PrimaryResourceID int NULL;

GO

ALTER TABLE WORKITEM_TASK
ADD CONSTRAINT [FK_WORKITEM_TASK_PrimaryResource] FOREIGN KEY ([PrimaryResourceID]) REFERENCES [WTS_RESOURCE]([WTS_RESOURCEID]);

GO
