USE WTS
GO

ALTER TABLE WORKITEM_TASK
ADD PRIORITYID int NULL;

GO

ALTER TABLE WORKITEM_TASK
ADD CONSTRAINT [FK_WORKITEM_TASK_PRIORITY] FOREIGN KEY ([PRIORITYID]) REFERENCES [PRIORITY]([PRIORITYID]);

GO
