USE WTS
GO

UPDATE WORKITEM_TASK
SET 
	WORKITEM_TASK.PRIMARYRESOURCEID = wi.PRIMARYRESOURCEID
FROM WORKITEM wi
WHERE 
	WORKITEM_TASK.WORKITEMID = wi.WORKITEMID
	AND WORKITEM_TASK.PRIMARYRESOURCEID IS NULL;

GO
