USE WTS
GO

INSERT INTO WORKITEMTYPE (WORKITEMTYPE, [DESCRIPTION], SORT_ORDER, ARCHIVE)
SELECT 'Sustainment Request', 'Used for items that represent a "Sustainment" request for the actual WTS system', 17, 0
EXCEPT SELECT WORKITEMTYPE, [DESCRIPTION], SORT_ORDER, ARCHIVE FROM WORKITEMTYPE;

GO

UPDATE WORKITEM
SET WORKITEMTYPEID = (SELECT WORKITEMTYPEID FROM WORKITEMTYPE WHERE WORKITEMTYPE = 'Sustainment Request')
WHERE WORKITEMID = 1;

GO
