USE WTS
GO

INSERT INTO WORKITEM(
	WORKITEMTYPEID
	, WTS_SYSTEMID
	, PRIORITYID
	, ALLOCATIONID
	, ASSIGNEDRESOURCEID
	, PRIMARYRESOURCEID
	, SECONDARYRESOURCEID
	, RESOURCEPRIORITYRANK
	, STATUSID
	, TITLE
	, [DESCRIPTION]
	, WORKREQUESTID
	, ProductVersionID
	, WorkTypeID
	, WorkloadGroupID
	, WorkAreaID
	, CREATEDBY
	, UPDATEDBY
	, SubmittedByID
)
SELECT 
	wi.WORKITEMTYPEID
	, wi.WTS_SYTEMID
	, wi.PRIORITYID
	, wi.ALLOCATIONID
	, wi.ASSIGNEDRESOURCEID
	, wi.PRIMARYRESOURCEID
	, wi.SECONDARYRESOURCEID
	, wi.RESOURCEPRIORITYRANK
	, wi.STATUSID
	, wit.WORKITEMTYPE + ' ' + wi.TITLE AS TITLE
	, wit.[DESCRIPTION] + ': <br/><br/>' + wi.[DESCRIPTION] AS [DESCRIPTION]
	, wi.WORKREQUESTID
	, wi.ProductVersionID
	, wi.WorkTypeID
	, wi.WorkloadGroupID
	, wi.WorkAreaID
	, wi.CREATEDBY
	, wi.UPDATEDBY
	, wi.SubmittedByID
FROM 
	( SELECT 
		(SELECT WORKITEMTYPEID FROM WORKITEMTYPE WHERE WORKITEMTYPE = 'Sustainment Request') AS WORKITEMTYPEID
		, (SELECT WTS_SYSTEMID FROM WTS_SYSTEM WHERE WTS_SYSTEM = 'WTS') AS WTS_SYTEMID
		, (SELECT PRIORITYID FROM [PRIORITY] WHERE [PRIORITY] = 'High' AND PRIORITYTYPEID = (SELECT PRIORITYTYPEID FROM PRIORITYTYPE WHERE PRIORITYTYPE = 'Work Item')) AS PRIORITYID
		, (SELECT ALLOCATIONID FROM ALLOCATION WHERE ALLOCATION = '15.2 - WTS') AS ALLOCATIONID
		, (SELECT WTS_RESOURCEID FROM WTS_RESOURCE WHERE USERNAME = 'Pete.McNamee') AS ASSIGNEDRESOURCEID
		, (SELECT WTS_RESOURCEID FROM WTS_RESOURCE WHERE USERNAME = 'Nick.Bailey') AS PRIMARYRESOURCEID
		, (SELECT WTS_RESOURCEID FROM WTS_RESOURCE WHERE USERNAME = 'Bryan.Arnett') AS SECONDARYRESOURCEID
		, 10 AS RESOURCEPRIORITYRANK
		, (SELECT STATUSID FROM [STATUS] WHERE [STATUS] = 'Info Requested') AS STATUSID
		, 'SR' AS TITLE
		, '"SRs" will be added as new Sub-Tasks.<div><br></div><div>Leads will determine if they warrant new workload items be created to handle the request.</div>' AS [DESCRIPTION]
		, (SELECT WORKREQUESTID FROM WORKREQUEST WHERE TITLE LIKE 'Workload Tracking System%') AS WORKREQUESTID
		, (SELECT ProductVersionID FROM ProductVersion WHERE ProductVersion = '15.2B') AS ProductVersionID
		, (SELECT WorkTypeID FROM WorkType WHERE WorkType = 'Build/Test') AS WorkTypeID
		, (SELECT WorkloadGroupID FROM WorkloadGroup WHERE WorkloadGroup LIKE 'Common%') AS WorkloadGroupID
		, (SELECT WorkAreaID FROM WorkArea WHERE WorkArea LIKE 'Common%') AS WorkAreaID
		, 'Pete.McNamee' AS CREATEDBY
		, 'Pete.McNamee' AS UPDATEDBY
		, (SELECT WTS_RESOURCEID FROM WTS_RESOURCE WHERE USERNAME = 'Pete.McNamee') AS SubmittedByID
	) wi
	, (SELECT 'Enhancement' AS WORKITEMTYPE, 'System Enhancement' AS [DESCRIPTION] UNION ALL
		SELECT 'Deficiency' AS WORKITEMTYPE, 'Work Stoppage, System Optimization' AS [DESCRIPTION] UNION ALL
		SELECT 'Data Update' AS WORKITEMTYPE, 'WTS System Data Update' AS [DESCRIPTION] UNION ALL
		SELECT 'Other Maintenance' AS WORKITEMTYPE, 'Other/Unspecified Maintenance' AS [DESCRIPTION] UNION ALL
		SELECT 'Process' AS WORKITEMTYPE, 'Discussion, Improvement or Support' AS [DESCRIPTION] UNION ALL
		SELECT 'Business Item' AS WORKITEMTYPE, 'Action item for business team or analysts to examine' AS [DESCRIPTION]
	) wit
EXCEPT SELECT WORKITEMTYPEID
	, WTS_SYSTEMID
	, PRIORITYID
	, ALLOCATIONID
	, ASSIGNEDRESOURCEID
	, PRIMARYRESOURCEID
	, SECONDARYRESOURCEID
	, RESOURCEPRIORITYRANK
	, STATUSID
	, TITLE
	, [DESCRIPTION]
	, WORKREQUESTID
	, ProductVersionID
	, WorkTypeID
	, WorkloadGroupID
	, WorkAreaID
	, CREATEDBY
	, UPDATEDBY
	, SubmittedByID FROM WORKITEM
;

GO
