use [WTS]
go

insert into PRIORITYTYPE (PRIORITYTYPE, [DESCRIPTION], SORT_ORDER)
select 'SR', 'SR', max(SORT_ORDER) + 1 from PRIORITYTYPE;

insert into [PRIORITY] (PRIORITYTYPEID, [PRIORITY], [DESCRIPTION], SORT_ORDER)
values ((select PRIORITYTYPEID from PRIORITYTYPE where PRIORITYTYPE = 'SR'), 'Low', 'Low', 1);

insert into [PRIORITY] (PRIORITYTYPEID, [PRIORITY], [DESCRIPTION], SORT_ORDER)
values ((select PRIORITYTYPEID from PRIORITYTYPE where PRIORITYTYPE = 'SR'), 'Medium', 'Medium', 2);

insert into [PRIORITY] (PRIORITYTYPEID, [PRIORITY], [DESCRIPTION], SORT_ORDER)
values ((select PRIORITYTYPEID from PRIORITYTYPE where PRIORITYTYPE = 'SR'), 'High', 'High', 3);
