use [WTS]
go

if [dbo].TableExists('dbo', 'WORKITEMTYPE_Status') = 0
begin
	CREATE TABLE [dbo].[WORKITEMTYPE_Status]
	(
		[WORKITEMTYPE_StatusID] INT IDENTITY NOT NULL PRIMARY KEY, 
		[WORKITEMTYPEID] INT NOT NULL, 
		[STATUSID] INT NOT NULL, 
		[SORT_ORDER] [int] NULL DEFAULT ((99)),
		[ARCHIVE] [bit] NOT NULL DEFAULT ((0)),
		[CREATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
		[CREATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
		[UPDATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
		[UPDATEDDATE] [datetime] NOT NULL DEFAULT (getdate()), 
		CONSTRAINT [FK_WORKITEMTYPE_Status_WORKITEMTYPE] FOREIGN KEY ([WORKITEMTYPEID]) REFERENCES [WORKITEMTYPE]([WORKITEMTYPEID]), 
		CONSTRAINT [FK_WORKITEMTYPE_Status_STATUS] FOREIGN KEY ([STATUSID]) REFERENCES [STATUS](STATUSID), 
		CONSTRAINT [UK_WORKITEMTYPE_Status_WORKITEMTYPESTATUS] UNIQUE ([WORKITEMTYPEID],[STATUSID])
	)
end;
go