use [WTS]
go

alter table WORKITEM_TASK
add WORKITEMTYPEID int not null DEFAULT (22);
go

ALTER TABLE [dbo].[WORKITEM_TASK]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_TASK_WORKITEMTYPEID] FOREIGN KEY([WORKITEMTYPEID])
REFERENCES [dbo].[WORKITEMTYPE] ([WORKITEMTYPEID])
GO