use [WTS]
go

UPDATE WORKITEM_TASK
SET STATUSID = 10
WHERE STATUSID = 70

UPDATE WORKITEM_TASK
SET STATUSID = 10
WHERE STATUSID = 15

UPDATE WORKITEM
SET STATUSID = 10
WHERE STATUSID = 70

UPDATE WORKITEM
SET STATUSID = 10
WHERE STATUSID = 15

DELETE FROM STATUS_PHASE
WHERE STATUSID = 15

DELETE FROM STATUS_WorkType
WHERE STATUSID = 15

DELETE FROM STATUS_WorkType
WHERE STATUSID = 70

DELETE FROM STATUS
WHERE STATUSID = 15

DELETE FROM STATUS
WHERE STATUSID = 70