USE WTS
GO

IF dbo.TableExists('dbo', 'RQMTSystemDefectTask') = 0
BEGIN
	CREATE TABLE dbo.RQMTSystemDefectTask
	(
		RQMTSystemDefectTaskID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
		RQMTSystemDefectID INT NOT NULL,
		WORKITEM_TASKID INT NOT NULL,
		CREATEDBY NVARCHAR(255) NOT NULL,
		CREATEDDATE DATETIME NOT NULL,
		UPDATEDBY NVARCHAR(255) NOT NULL,
		UPDATEDDATE DATETIME NOT NULL
	)

	CREATE NONCLUSTERED INDEX [IDX_RQMTSystemDefectTask] ON [dbo].RQMTSystemDefectTask(WORKITEM_TASKID ASC)
	CREATE NONCLUSTERED INDEX [IDX_RQMTSystemDefectTask_Defect] ON [dbo].RQMTSystemDefectTask(RQMTSystemDefectID ASC)

	ALTER TABLE [dbo].RQMTSystemDefectTask ADD CONSTRAINT [FK_RQMTSystemDefectTask] FOREIGN KEY(WORKITEM_TASKID) REFERENCES dbo.WORKITEM_TASK(WORKITEM_TASKID)
	ALTER TABLE [dbo].RQMTSystemDefectTask ADD CONSTRAINT [FK_RQMTSystemDefectTask_Defect] FOREIGN KEY(RQMTSystemDefectID) REFERENCES dbo.RQMTSystemDefect(RQMTSystemDefectID)		
END