use WTS
IF dbo.ColumnExists('dbo','WTS_SYSTEM_SUITE','WTS_SYSTEM_SUITE') = 1
BEGIN
	ALTER TABLE dbo.[WTS_SYSTEM_SUITE]
        ALTER COLUMN [WTS_SYSTEM_SUITE] NVARCHAR(2000) NOT NULL;
END

IF dbo.ColumnExists('dbo','WTS_SYSTEM_SUITE','DESCRIPTION') = 1
BEGIN
ALTER TABLE dbo.[WTS_SYSTEM_SUITE]
        ALTER COLUMN [DESCRIPTION] NVARCHAR(2000) NOT NULL
END

IF dbo.ColumnExists('dbo','WTS_SYSTEM','WTS_SYSTEM') = 1
BEGIN
	ALTER TABLE dbo.[WTS_SYSTEM]
        ALTER COLUMN [WTS_SYSTEM] NVARCHAR(2000) NOT NULL
END

IF dbo.ColumnExists('dbo','WTS_SYSTEM','DESCRIPTION') = 1
BEGIN
	ALTER TABLE dbo.[WTS_SYSTEM]
        ALTER COLUMN [DESCRIPTION] NVARCHAR(2000) NOT NULL
END

GO