use [WTS]
go

alter table WORKITEMTYPE
add PDDTDR_PHASEID int not null DEFAULT (9);
go

ALTER TABLE [dbo].[WORKITEMTYPE]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEMTYPE_PDDTDR_PHASEID] FOREIGN KEY([PDDTDR_PHASEID])
REFERENCES [dbo].[PDDTDR_PHASE] ([PDDTDR_PHASEID])
GO