USE WTS
GO

IF dbo.ColumnExists('dbo', 'RQMTSet', 'RQMTComplexityID') = 0
BEGIN
	ALTER TABLE RQMTSet ADD RQMTComplexityID INT NOT NULL DEFAULT 8	
	ALTER TABLE RQMTSet ADD Justification NVARCHAR(1000) NULL

	ALTER TABLE [dbo].[RQMTSet]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSet_Complexity] FOREIGN KEY(RQMTComplexityID)
	REFERENCES [dbo].RQMTComplexity (RQMTComplexityID)
END