USE WTS
GO

DECLARE @dt DATETIME = GETDATE()
DECLARE @newID INT = 0

IF NOT EXISTS (SELECT 1 FROM PRIORITYTYPE WHERE PRIORITYTYPE = 'RQMT')
BEGIN
	INSERT INTO PRIORITYTYPE VALUES ('RQMT', 'RQMT', 7, 0, 'WTS_ADMIN', @dt, 'WTS_ADMIN', @dt)
	SET @newID = SCOPE_IDENTITY()

	INSERT INTO PRIORITY VALUES (@newID, 'Critical', 'Critical', 1, 0, 'WTS_ADMIN', @dt, 'WTS_ADMIN', @dt)
	INSERT INTO PRIORITY VALUES (@newID, 'Major', 'Major', 2, 0, 'WTS_ADMIN', @dt, 'WTS_ADMIN', @dt)
	INSERT INTO PRIORITY VALUES (@newID, 'Minor', 'Minor', 3, 0, 'WTS_ADMIN', @dt, 'WTS_ADMIN', @dt)

	CREATE INDEX IDX_RQMTSystem_RQMT ON dbo.RQMTSystem
	(
		RQMTID
	)

	ALTER TABLE dbo.RQMTSystem ADD PRIORITYID INT
END

