USE WTS
GO

IF dbo.TableExists('dbo', 'RQMTSet_Task') = 0
BEGIN

	CREATE TABLE dbo.RQMTSet_Task
	(
		RQMTSetTaskID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
		RQMTSetID INT NOT NULL,
		WORKITEM_TASKID INT NOT NULL,
		CREATEDBY NVARCHAR(255) NOT NULL,
		CREATEDDATE DATETIME NOT NULL,
		UPDATEDBY NVARCHAR(255) NOT NULL,
		UPDATEDDATE DATETIME NOT NULL		
	)

	CREATE NONCLUSTERED INDEX [IDX_RQMTSetTask] ON [dbo].RQMTSet_Task(WORKITEM_TASKID ASC)
	CREATE NONCLUSTERED INDEX [IDX_RQMTSetTask_RQMTSet] ON [dbo].RQMTSet_Task(RQMTSetID ASC, WORKITEM_TASKID ASC)

	ALTER TABLE [dbo].RQMTSet_Task ADD CONSTRAINT [FK_RQMTSetTask] FOREIGN KEY(WORKITEM_TASKID) REFERENCES dbo.WORKITEM_TASK(WORKITEM_TASKID)
	ALTER TABLE [dbo].RQMTSet_Task ADD CONSTRAINT [FK_RQMTSetTask_Set] FOREIGN KEY(RQMTSetID) REFERENCES dbo.RQMTSet(RQMTSetID)
END