USE WTS
GO

IF dbo.ColumnExists('dbo', 'AORMeetingNotes', 'WORKITEMID') = 0
BEGIN
	ALTER TABLE dbo.AORMeetingNotes ADD
		WORKITEMID INT NULL,
		WORKITEM_TASKID INT NULL

	ALTER TABLE dbo.AORMeetingNotes  WITH CHECK ADD CONSTRAINT FK_AORMeetingNotes_WorkItem FOREIGN KEY(WORKITEMID)
	REFERENCES [dbo].WORKITEM (WORKITEMID)

	ALTER TABLE dbo.AORMeetingNotes  WITH CHECK ADD CONSTRAINT FK_AORMeetingNotes_WorkItem_Task FOREIGN KEY(WORKITEM_TASKID)
	REFERENCES [dbo].WORKITEM_TASK (WORKITEM_TASKID)
END