USE WTS
GO

IF dbo.TableExists('dbo', 'RQMTSystemDefectSR') = 0
BEGIN
	CREATE TABLE dbo.RQMTSystemDefectSR
	(
		RQMTSystemDefectSRID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
		RQMTSystemDefectID INT NOT NULL,
		SRID INT NULL,
		AORSR_SRID INT NULL
	)

	CREATE NONCLUSTERED INDEX [IDX_RQMTSystemDefectSR_Defect] ON [dbo].RQMTSystemDefectSR(RQMTSystemDefectID ASC)
	CREATE NONCLUSTERED INDEX [IDX_RQMTSystemDefectSR_SR] ON [dbo].RQMTSystemDefectSR(SRID ASC)
	CREATE NONCLUSTERED INDEX [IDX_RQMTSystemDefectSR_AORSR] ON [dbo].RQMTSystemDefectSR(AORSR_SRID ASC)

	ALTER TABLE [dbo].RQMTSystemDefectSR  WITH CHECK ADD CONSTRAINT [FK_RQMTSystemDefectSR_Defect] FOREIGN KEY(RQMTSystemDefectID) REFERENCES dbo.RQMTSystemDefect(RQMTSystemDefectID)
	ALTER TABLE [dbo].RQMTSystemDefectSR  WITH CHECK ADD CONSTRAINT [FK_RQMTSystemDefectSR_SR] FOREIGN KEY(SRID) REFERENCES dbo.SR(SRID)
	ALTER TABLE [dbo].RQMTSystemDefectSR  WITH CHECK ADD CONSTRAINT [FK_RQMTSystemDefectSR_AORSR] FOREIGN KEY(AORSR_SRID) REFERENCES dbo.AORSR(SRID)
END
