USE WTS

GO

CREATE TABLE [dbo].[Allocation_System]
(
	[Allocation_SystemId] INT IDENTITY NOT NULL PRIMARY KEY, 
    [ALLOCATIONID] INT NOT NULL, 
    [WTS_SYSTEMID] INT NULL,
    [Description] NVARCHAR(MAX) NULL,
	[ProposedPriority] INT NULL DEFAULT 99, 
    [ApprovedPriority] INT NULL DEFAULT 99,
	[SORT_ORDER] [int] NULL DEFAULT ((99)),
	[ARCHIVE] [bit] NOT NULL DEFAULT ((0)),
	[CREATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[CREATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[UPDATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[UPDATEDDATE] [datetime] NOT NULL DEFAULT (getdate()), 
    CONSTRAINT [AK_Allocation_System_Unique] UNIQUE ([ALLOCATIONID],[WTS_SYSTEMID]), 
    CONSTRAINT [FK_Allocation_System_ALLOCATION] FOREIGN KEY ([ALLOCATIONID]) REFERENCES [ALLOCATION]([ALLOCATIONID]), 
    CONSTRAINT [FK_Allocation_System_WTS_SYSTEM] FOREIGN KEY ([WTS_SYSTEMID]) REFERENCES [WTS_SYSTEM]([WTS_SYSTEMID])
)


GO
