USE WTS
GO

ALTER TABLE ALLOCATION
ADD [DefaultSMEID] INT NULL
, [DefaultBusinessResourceID] INT NULL
, [DefaultTechnicalResourceID] INT NULL;

GO

ALTER TABLE ALLOCATION
ADD CONSTRAINT [FK_ALLOCATION_SME] FOREIGN KEY ([DefaultSMEID]) REFERENCES [WTS_RESOURCE]([WTS_RESOURCEID]);

GO

ALTER TABLE ALLOCATION
ADD CONSTRAINT [FK_ALLOCATION_BusinessResource] FOREIGN KEY ([DefaultBusinessResourceID]) REFERENCES [WTS_RESOURCE]([WTS_RESOURCEID]);

GO

ALTER TABLE ALLOCATION
ADD CONSTRAINT [FK_ALLOCATION_TechnicalResource] FOREIGN KEY ([DefaultTechnicalResourceID]) REFERENCES [WTS_RESOURCE]([WTS_RESOURCEID]);

GO

