USE WTS
GO

ALTER TABLE ALLOCATION
ADD [DefaultAssignedToID] INT NULL;

GO

ALTER TABLE ALLOCATION
ADD CONSTRAINT [FK_ALLOCATION_AssignedTo] FOREIGN KEY ([DefaultAssignedToID]) REFERENCES [WTS_RESOURCE]([WTS_RESOURCEID]);

GO
