ALTER TABLE [WTS].[dbo].[ALLOCATION] ADD ALLOCATIONGROUPID int NULL
go


ALTER TABLE [WTS].[dbo].[ALLOCATION]
ADD CONSTRAINT [FK_ALLOCATION_GROUPID] FOREIGN KEY([ALLOCATIONGROUPID]) REFERENCES [AllocationGroup]([ALLOCATIONGROUPID])