use wts
go

--INSERT NEW ASSIGNED TO AND CUSTOMER RANK TYPE
INSERT INTO [PRIORITYTYPE]([PRIORITYTYPE],[DESCRIPTION],[SORT_ORDER])
VALUES ('Rank', 'Rank for assigned to and customer resources', 5);

--INSERT NEW ASSIGNED TO AND CUSTOMER RANKS
INSERT INTO [PRIORITY]([PRIORITYTYPEID],[PRIORITY],[DESCRIPTION],[SORT_ORDER])
VALUES (5,'1 - Emergency Workload', '1 - Emergency Workload', 1);

INSERT INTO [PRIORITY]([PRIORITYTYPEID],[PRIORITY],[DESCRIPTION],[SORT_ORDER])
VALUES (5,'2 - Current Workload', '2 - Current Workload', 2);

INSERT INTO [PRIORITY]([PRIORITYTYPEID],[PRIORITY],[DESCRIPTION],[SORT_ORDER])
VALUES (5,'3 - Staged Workload', '3 - Staged Workload', 3);

INSERT INTO [PRIORITY]([PRIORITYTYPEID],[PRIORITY],[DESCRIPTION],[SORT_ORDER])
VALUES (5,'4 - Unprioritized Workload', '4 - Unprioritized Workload', 4);

INSERT INTO [PRIORITY]([PRIORITYTYPEID],[PRIORITY],[DESCRIPTION],[SORT_ORDER])
VALUES (5,'5 - Closed Workload', '5 - Closed Workload', 5);

ALTER TABLE WORKITEM
ADD AssignedToRankID int;

ALTER TABLE WORKITEM
ADD CONSTRAINT [FK_WORKITEM_AssignedToRank] FOREIGN KEY (AssignedToRankID) REFERENCES [PRIORITY]([PRIORITYID]);

ALTER TABLE WORKITEM_TASK
ADD AssignedToRankID int;

ALTER TABLE WORKITEM_TASK
ADD CONSTRAINT [FK_WORKITEM_TASK_AssignedToRank] FOREIGN KEY (AssignedToRankID) REFERENCES [PRIORITY]([PRIORITYID]);

UPDATE WORKITEM
SET AssignedToRankID = (SELECT DISTINCT
CASE when isnull([RESOURCEPRIORITYRANK],4) = 0 then 27
when isnull([RESOURCEPRIORITYRANK],4) = 1 then 27
when isnull([RESOURCEPRIORITYRANK],4) = 2 then 28
when isnull([RESOURCEPRIORITYRANK],4) = 3 then 29
when isnull([RESOURCEPRIORITYRANK],4) >= 4 then 30 end
FROM WORKITEM wi
	WHERE wi.WORKITEMID = WORKITEM.WORKITEMID);

UPDATE WORKITEM
SET AssignedToRankID = 31
WHERE STATUSID = 10;

UPDATE WORKITEM
SET [RESOURCEPRIORITYRANK] = 99
WHERE STATUSID = 10;


UPDATE WORKITEM_TASK
SET AssignedToRankID = (SELECT DISTINCT
CASE when isnull([SORT_ORDER],4) = 0 then 27
when isnull([SORT_ORDER],4) = 1 then 27
when isnull([SORT_ORDER],4) = 2 then 28
when isnull([SORT_ORDER],4) = 3 then 29
when isnull([SORT_ORDER],4) >= 4 then 30 end
  FROM WORKITEM_TASK wit
	WHERE wit.WORKITEM_TASKID = WORKITEM_TASK.WORKITEM_TASKID);

UPDATE WORKITEM_TASK
SET AssignedToRankID = 31
WHERE STATUSID = 10;

UPDATE WORKITEM_TASK
SET [SORT_ORDER] = 99
WHERE STATUSID = 10;

UPDATE WORKITEM_TASK
SET [BusinessRank] = 99
WHERE STATUSID = 10;

UPDATE WORKITEM
SET [PrimaryBusinessRank] = 99
WHERE STATUSID = 10;
