USE WTS



ALTER TABLE WORKITEM
ADD PDDTDR_PHASEID INT NULL
	CONSTRAINT [FK_WORKITEM_PDDTDR_PHASE] FOREIGN KEY ([PDDTDR_PHASEID]) REFERENCES [PDDTDR_PHASE]([PDDTDR_PHASEID]) 

UPDATE WORKITEM
SET WORKITEM.PDDTDR_PHASEID = WORKREQUEST.PROGRESSID
FROM WORKREQUEST
WHERE WORKITEM.WORKREQUESTID = WORKREQUEST.WORKREQUESTID


ALTER TABLE WORKREQUEST
DROP CONSTRAINT [FK_WORKREQUEST_PDDTDR_PHASE]

ALTER TABLE WORKREQUEST DROP COLUMN PROGRESSID

UPDATE GridView
SET Tier2ColumnOrder = REPLACE(Tier2ColumnOrder, 'RequestPhase', 'Phase')