-- EVENT TYPE
CREATE TABLE dbo.EVENT_TYPE
(
	EVENT_TYPEID INT NOT NULL PRIMARY KEY,
	EventType VARCHAR(100) NOT NULL
)
GO

INSERT INTO dbo.EVENT_TYPE VALUES (1, 'Email')
INSERT INTO dbo.EVENT_TYPE VALUES (2, 'CleanEventQueue')
INSERT INTO dbo.EVENT_TYPE VALUES (3, 'RunReport')
GO



-- EVENT STATUS
CREATE TABLE dbo.EVENT_STATUS
(
	EVENT_STATUSID INT NOT NULL PRIMARY KEY,
	EventStatus VARCHAR(100) NOT NULL
)
GO

INSERT INTO dbo.EVENT_STATUS VALUES (1, 'Scheduled')
INSERT INTO dbo.EVENT_STATUS VALUES (2, 'Executing')
INSERT INTO dbo.EVENT_STATUS VALUES (3, 'Complete')
INSERT INTO dbo.EVENT_STATUS VALUES (9, 'Error')
GO



-- EVENT QUEUE
CREATE TABLE dbo.EventQueue
(
	EventQueueID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	EVENT_TYPEID INT NOT NULL,
	EVENT_STATUSID INT NOT NULL,
	ScheduledDate DATETIME NOT NULL,	
	CompletedDate DATETIME NULL,	
	Payload NVARCHAR(MAX) NULL,
	CreatedBy NVARCHAR(255) NOT NULL,
	CreatedDate DATETIME NOT NULL,	
	Result NVARCHAR(MAX) NULL,
	Error NVARCHAR(MAX) NULL
)

CREATE INDEX IDX_EventQueueType
ON dbo.EventQueue (EVENT_TYPEID, EVENT_STATUSID)

CREATE INDEX IDX_EventQueueStatus
ON dbo.EventQueue (EVENT_STATUSID, ScheduledDate)

CREATE INDEX IDX_EventQueueSchedule
ON dbo.EventQueue (ScheduledDate)

ALTER TABLE dbo.EventQueue  WITH CHECK ADD CONSTRAINT [FK_EventQueue_EventType] FOREIGN KEY([EVENT_TYPEID])
REFERENCES [dbo].EVENT_TYPE (EVENT_TYPEID)

ALTER TABLE dbo.EventQueue  WITH CHECK ADD CONSTRAINT [FK_EventQueue_EventStatus] FOREIGN KEY([EVENT_STATUSID])
REFERENCES [dbo].EVENT_STATUS (EVENT_STATUSID)

GO

-- REPORT STATUS
CREATE TABLE dbo.REPORT_STATUS
(
	REPORT_STATUSID INT NOT NULL PRIMARY KEY,
	ReportStatus VARCHAR(100) NOT NULL
)
GO

INSERT INTO dbo.REPORT_STATUS VALUES (1, 'Queued')
INSERT INTO dbo.REPORT_STATUS VALUES (2, 'Executing')
INSERT INTO dbo.REPORT_STATUS VALUES (3, 'Complete')
INSERT INTO dbo.REPORT_STATUS VALUES (9, 'Error')
GO

-- REPORT TYPE
CREATE TABLE dbo.REPORT_TYPE
(
	REPORT_TYPEID INT NOT NULL PRIMARY KEY,
	ReportType VARCHAR(100) NOT NULL
)
GO

INSERT INTO dbo.REPORT_TYPE VALUES (0, 'External')
INSERT INTO dbo.REPORT_TYPE VALUES (1, 'Workload Summary Report')
INSERT INTO dbo.REPORT_TYPE VALUES (2, 'CR Report')

-- REPORT QUEUE

CREATE TABLE dbo.ReportQueue
(
	ReportQueueID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Guid VARCHAR(50) NOT NULL,
	WTS_RESOURCEID INT NOT NULL,
	REPORT_TYPEID INT NOT NULL,
	REPORT_STATUSID INT NOT NULL,
	ReportName NVARCHAR(255) NULL,
	ReportAssembly VARCHAR(255) NULL,
	ReportClass VARCHAR(255) NULL,
	ReportMethod VARCHAR(255) NULL,
	ScheduledDate DATETIME NULL,
	CompletedDate DATETIME NULL,	
	ReportParameters NVARCHAR(MAX) NULL,
	CreatedBy NVARCHAR(255) NOT NULL,
	CreatedDate DATETIME NOT NULL,
	Result NVARCHAR(MAX) NULL,
	Error NVARCHAR(MAX) NULL,
	OutFileName VARCHAR(100) NULL,
	OutFile VARBINARY(MAX) NULL,
	Archive BIT NOT NULL
)

CREATE INDEX IDX_ReportQueueGuid
ON dbo.ReportQueue (Guid)

CREATE INDEX IDX_ReportQueueResource
ON dbo.ReportQueue (WTS_RESOURCEID)

CREATE INDEX IDX_ReportQueueArchive
ON dbo.ReportQueue (Archive)

CREATE INDEX IDX_ReportQueueStatus
ON dbo.ReportQueue (REPORT_STATUSID, WTS_RESOURCEID)

CREATE INDEX IDX_ReportQueueSchedule
ON dbo.ReportQueue (ScheduledDate)

CREATE INDEX IDX_ReportQueueStatusSchedule
ON dbo.ReportQueue (REPORT_STATUSID, ScheduledDate)

ALTER TABLE dbo.ReportQueue  WITH CHECK ADD CONSTRAINT [FK_ReportQueue_Resource] FOREIGN KEY([WTS_RESOURCEID])
REFERENCES [dbo].WTS_RESOURCE (WTS_RESOURCEID)

ALTER TABLE dbo.ReportQueue  WITH CHECK ADD CONSTRAINT [FK_ReportQueue_Type] FOREIGN KEY([REPORT_TYPEID])
REFERENCES [dbo].REPORT_TYPE (REPORT_TYPEID)

ALTER TABLE dbo.ReportQueue  WITH CHECK ADD CONSTRAINT [FK_ReportQueue_ReportStatus] FOREIGN KEY([REPORT_STATUSID])
REFERENCES [dbo].REPORT_STATUS (REPORT_STATUSID)


