USE WTS
GO

WITH A AS (
SELECT ALLOCATIONID
FROM ALLOCATION
WHERE 
ALLOCATION = '13.2 CF' OR
ALLOCATION = '13.2 CLIN & Contract - POP' OR
ALLOCATION = '13.2 Coord' OR
ALLOCATION = '13.2 CRIS' OR
ALLOCATION = '13.2 ICD/ACFT HEALTH' OR
ALLOCATION = '13.2 PTS 19821' OR
ALLOCATION = '13.2 XWalk FundsSp' OR
ALLOCATION = '14.1A AMR Collab' OR
ALLOCATION = '14.1A SRA Software Methodology' OR
ALLOCATION = '14.1A Support' OR
ALLOCATION = '14.1B Support' OR
ALLOCATION = '14.1B User Mgmt Registration' OR
ALLOCATION = '14.1B WSMS - Rpts/Datasheets' OR
ALLOCATION = '14.1B WSMS - WCN/Task Main' OR
ALLOCATION = '14.1B WSMS - WSMS CAFDEx Collab' OR
ALLOCATION = '14.2 1269' OR
ALLOCATION = '14.2 CAFDEx News' OR
ALLOCATION = '14.2 CF' OR
ALLOCATION = '14.2 CP' OR
ALLOCATION = '14.2 CRIS' OR
ALLOCATION = '14.2 OOC/Variance Tracking' OR
ALLOCATION = '14.2 Usability and Modernization' OR
ALLOCATION = '14.2 Work Spec' OR
ALLOCATION = 'Flying Hours' OR
ALLOCATION = 'CAFDEx Restructure' OR
ALLOCATION = 'Delete No Action Comments (CAFDEx)' OR
ALLOCATION = 'SRMA Rehost' OR
ALLOCATION = 'WSMS Rehost Phase 2' OR
ALLOCATION = 'SRMA Supp' OR
ALLOCATION = 'UID Supp' OR
ALLOCATION = '14.2 Doc' OR
ALLOCATION = 'Catholic University' OR
ALLOCATION = 'FHP Funding Module' OR
ALLOCATION = 'FHP Hours Module' OR
ALLOCATION = 'FHP WRDCO (R&D)' OR
ALLOCATION = 'Funds Source Maintenance' OR
ALLOCATION = 'Maint Grids' OR
ALLOCATION = 'Production Support' OR
ALLOCATION = 'QM Grids' OR
ALLOCATION = 'FRM Reports/Datasheets' OR
ALLOCATION = 'Program Group Rollback')
UPDATE WORKITEM
SET
	ALLOCATIONID = NULL
WHERE
	ALLOCATIONID IN (SELECT * FROM A);



USE WTS
GO

UPDATE ALLOCATION
SET ARCHIVE = 1,
	ALLOCATIONGROUPID = NULL
WHERE 
ALLOCATION = '13.2 CF' OR
ALLOCATION = '13.2 CLIN & Contract - POP' OR
ALLOCATION = '13.2 Coord' OR
ALLOCATION = '13.2 CRIS' OR
ALLOCATION = '13.2 ICD/ACFT HEALTH' OR
ALLOCATION = '13.2 PTS 19821' OR
ALLOCATION = '13.2 XWalk FundsSp' OR
ALLOCATION = '14.1A AMR Collab' OR
ALLOCATION = '14.1A SRA Software Methodology' OR
ALLOCATION = '14.1A Support' OR
ALLOCATION = '14.1B Support' OR
ALLOCATION = '14.1B User Mgmt Registration' OR
ALLOCATION = '14.1B WSMS - Rpts/Datasheets' OR
ALLOCATION = '14.1B WSMS - WCN/Task Main' OR
ALLOCATION = '14.1B WSMS - WSMS CAFDEx Collab' OR
ALLOCATION = '14.2 1269' OR
ALLOCATION = '14.2 CAFDEx News' OR
ALLOCATION = '14.2 CF' OR
ALLOCATION = '14.2 CP' OR
ALLOCATION = '14.2 CRIS' OR
ALLOCATION = '14.2 OOC/Variance Tracking' OR
ALLOCATION = '14.2 Usability and Modernization' OR
ALLOCATION = '14.2 Work Spec' OR
ALLOCATION = 'Flying Hours' OR
ALLOCATION = 'CAFDEx Restructure' OR
ALLOCATION = 'Delete No Action Comments (CAFDEx)' OR
ALLOCATION = 'SRMA Rehost' OR
ALLOCATION = 'WSMS Rehost Phase 2' OR
ALLOCATION = 'SRMA Supp' OR
ALLOCATION = 'UID Supp' OR
ALLOCATION = '14.2 Doc' OR
ALLOCATION = 'Catholic University' OR
ALLOCATION = 'FHP Funding Module' OR
ALLOCATION = 'FHP Hours Module' OR
ALLOCATION = 'FHP WRDCO (R&D)' OR
ALLOCATION = 'Funds Source Maintenance' OR
ALLOCATION = 'Maint Grids' OR
ALLOCATION = 'Production Support' OR
ALLOCATION = 'QM Grids' OR
ALLOCATION = 'FRM Reports/Datasheets' OR
ALLOCATION = 'Program Group Rollback';


USE WTS
GO
USE WTS
GO

WITH A AS (
SELECT ALLOCATIONID
FROM ALLOCATION
WHERE 
ALLOCATION = '13.2 CF' OR
ALLOCATION = '13.2 CLIN & Contract - POP' OR
ALLOCATION = '13.2 Coord' OR
ALLOCATION = '13.2 CRIS' OR
ALLOCATION = '13.2 ICD/ACFT HEALTH' OR
ALLOCATION = '13.2 PTS 19821' OR
ALLOCATION = '13.2 XWalk FundsSp' OR
ALLOCATION = '14.1A AMR Collab' OR
ALLOCATION = '14.1A SRA Software Methodology' OR
ALLOCATION = '14.1A Support' OR
ALLOCATION = '14.1B Support' OR
ALLOCATION = '14.1B User Mgmt Registration' OR
ALLOCATION = '14.1B WSMS - Rpts/Datasheets' OR
ALLOCATION = '14.1B WSMS - WCN/Task Main' OR
ALLOCATION = '14.1B WSMS - WSMS CAFDEx Collab' OR
ALLOCATION = '14.2 1269' OR
ALLOCATION = '14.2 CAFDEx News' OR
ALLOCATION = '14.2 CF' OR
ALLOCATION = '14.2 CP' OR
ALLOCATION = '14.2 CRIS' OR
ALLOCATION = '14.2 OOC/Variance Tracking' OR
ALLOCATION = '14.2 Usability and Modernization' OR
ALLOCATION = '14.2 Work Spec' OR
ALLOCATION = 'Flying Hours' OR
ALLOCATION = 'CAFDEx Restructure' OR
ALLOCATION = 'Delete No Action Comments (CAFDEx)' OR
ALLOCATION = 'SRMA Rehost' OR
ALLOCATION = 'WSMS Rehost Phase 2' OR
ALLOCATION = 'SRMA Supp' OR
ALLOCATION = 'UID Supp' OR
ALLOCATION = '14.2 Doc' OR
ALLOCATION = 'Catholic University' OR
ALLOCATION = 'FHP Funding Module' OR
ALLOCATION = 'FHP Hours Module' OR
ALLOCATION = 'FHP WRDCO (R&D)' OR
ALLOCATION = 'Funds Source Maintenance' OR
ALLOCATION = 'Maint Grids' OR
ALLOCATION = 'Production Support' OR
ALLOCATION = 'QM Grids' OR
ALLOCATION = 'FRM Reports/Datasheets' OR
ALLOCATION = 'Program Group Rollback')
DELETE Allocation_System
WHERE ALLOCATIONID IN (SELECT * FROM A);



USE WTS
GO
DELETE FROM ALLOCATION
WHERE 
ALLOCATION = '13.2 CF' OR
ALLOCATION = '13.2 CLIN & Contract - POP' OR
ALLOCATION = '13.2 Coord' OR
ALLOCATION = '13.2 CRIS' OR
ALLOCATION = '13.2 ICD/ACFT HEALTH' OR
ALLOCATION = '13.2 PTS 19821' OR
ALLOCATION = '13.2 XWalk FundsSp' OR
ALLOCATION = '14.1A AMR Collab' OR
ALLOCATION = '14.1A SRA Software Methodology' OR
ALLOCATION = '14.1A Support' OR
ALLOCATION = '14.1B Support' OR
ALLOCATION = '14.1B User Mgmt Registration' OR
ALLOCATION = '14.1B WSMS - Rpts/Datasheets' OR
ALLOCATION = '14.1B WSMS - WCN/Task Main' OR
ALLOCATION = '14.1B WSMS - WSMS CAFDEx Collab' OR
ALLOCATION = '14.2 1269' OR
ALLOCATION = '14.2 CAFDEx News' OR
ALLOCATION = '14.2 CF' OR
ALLOCATION = '14.2 CP' OR
ALLOCATION = '14.2 CRIS' OR
ALLOCATION = '14.2 OOC/Variance Tracking' OR
ALLOCATION = '14.2 Usability and Modernization' OR
ALLOCATION = '14.2 Work Spec' OR
ALLOCATION = 'Flying Hours' OR
ALLOCATION = 'CAFDEx Restructure' OR
ALLOCATION = 'Delete No Action Comments (CAFDEx)' OR
ALLOCATION = 'SRMA Rehost' OR
ALLOCATION = 'WSMS Rehost Phase 2' OR
ALLOCATION = 'SRMA Supp' OR
ALLOCATION = 'UID Supp' OR
ALLOCATION = '14.2 Doc' OR
ALLOCATION = 'Catholic University' OR
ALLOCATION = 'FHP Funding Module' OR
ALLOCATION = 'FHP Hours Module' OR
ALLOCATION = 'FHP WRDCO (R&D)' OR
ALLOCATION = 'Funds Source Maintenance' OR
ALLOCATION = 'Maint Grids' OR
ALLOCATION = 'Production Support' OR
ALLOCATION = 'QM Grids' OR
ALLOCATION = 'FRM Reports/Datasheets' OR
ALLOCATION = 'Program Group Rollback';
GO
