USE WTS
GO

ALTER TABLE [dbo].[COMMENT] DROP CONSTRAINT [FK_COMMENT_THREAD]
GO

ALTER TABLE [dbo].[COMMENT] DROP CONSTRAINT [FK_COMMENT_PARENT]
GO

/****** Object:  Table [dbo].[COMMENT]    Script Date: 7/2/2015 2:05:38 PM ******/
DROP TABLE [dbo].[COMMENT]
GO

/****** Object:  Table [dbo].[COMMENT]    Script Date: 7/2/2015 2:05:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMMENT](
	[COMMENTID] [int] IDENTITY(1,1) NOT NULL,
	[PARENTID] [int] NULL,
	[THREAD_COMMENTID] [int] NULL,
	[COMMENT_TEXT] [nvarchar](max) NOT NULL,
	[SORT_ORDER] [int] NULL DEFAULT ((99)),
	[ARCHIVE] [bit] NOT NULL DEFAULT ((0)),
	[CREATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[CREATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[UPDATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[UPDATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[BUG_POSTID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[COMMENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[COMMENT]  WITH CHECK ADD  CONSTRAINT [FK_COMMENT_PARENT] FOREIGN KEY([PARENTID])
REFERENCES [dbo].[COMMENT] ([COMMENTID])
GO

ALTER TABLE [dbo].[COMMENT] CHECK CONSTRAINT [FK_COMMENT_PARENT]
GO

ALTER TABLE [dbo].[COMMENT]  WITH CHECK ADD  CONSTRAINT [FK_COMMENT_THREAD] FOREIGN KEY([THREAD_COMMENTID])
REFERENCES [dbo].[COMMENT] ([COMMENTID])
GO

ALTER TABLE [dbo].[COMMENT] CHECK CONSTRAINT [FK_COMMENT_THREAD]
GO

