USE WTS
GO

ALTER TABLE [dbo].[CONFIGSETTING] DROP CONSTRAINT [FK_CONFIGSETTING_CONFIGSETTING_TYPE]
GO

/****** Object:  Table [dbo].[CONFIGSETTING]    Script Date: 7/2/2015 2:06:11 PM ******/
DROP TABLE [dbo].[CONFIGSETTING]
GO

/****** Object:  Table [dbo].[CONFIGSETTING]    Script Date: 7/2/2015 2:06:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONFIGSETTING](
	[CONFIGSETTINGID] [int] IDENTITY(1,1) NOT NULL,
	[CONFIGSETTINGTYPEID] [int] NOT NULL,
	[PARENTSETTINGID] [int] NULL DEFAULT (NULL),
	[SETTINGVALUE] [nvarchar](255) NULL DEFAULT (''),
	[ARCHIVE] [bit] NOT NULL DEFAULT ((0)),
	[DESCRIPTION] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[CONFIGSETTINGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[CONFIGSETTING]  WITH CHECK ADD  CONSTRAINT [FK_CONFIGSETTING_CONFIGSETTING_TYPE] FOREIGN KEY([CONFIGSETTINGTYPEID])
REFERENCES [dbo].[CONFIGSETTING_TYPE] ([CONFIGSETTING_TYPEID])
GO

ALTER TABLE [dbo].[CONFIGSETTING] CHECK CONSTRAINT [FK_CONFIGSETTING_CONFIGSETTING_TYPE]
GO

