USE WTS
GO

/****** Object:  Table [dbo].[EMAIL_STATUS_TYPE]    Script Date: 7/2/2015 2:03:51 PM ******/
DROP TABLE [dbo].[EMAIL_STATUS_TYPE]
GO

/****** Object:  Table [dbo].[EMAIL_STATUS_TYPE]    Script Date: 7/2/2015 2:03:51 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMAIL_STATUS_TYPE](
	[EMAIL_STATUS_TYPEID] [int] IDENTITY(1,1) NOT NULL,
	[STATUS] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NULL,
	[ARCHIVE] [bit] NOT NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[EMAIL_STATUS_TYPEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

