USE [WTS]
GO

ALTER TABLE [dbo].[GridView] DROP CONSTRAINT [FK_GridView_GridName]
GO

ALTER TABLE [dbo].[GridView] DROP CONSTRAINT [DF__GridView__Archiv__54575F1A]
GO

ALTER TABLE [dbo].[GridView] DROP CONSTRAINT [DF__GridView__SORT_O__53633AE1]
GO

/****** Object:  Table [dbo].[GridView]    Script Date: 8/11/2015 11:05:03 AM ******/
DROP TABLE [dbo].[GridView]
GO

/****** Object:  Table [dbo].[GridView]    Script Date: 8/11/2015 11:05:03 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GridView](
	[GridViewID] [int] IDENTITY(1,1) NOT NULL,
	[GridNameID] [int] NOT NULL,
	[WTS_RESOURCEID] INT NULL, 
    [SessionID] NVARCHAR(100) NULL, 
	[ViewName] [nvarchar](50) NOT NULL,
    [DefaultSelection] BIT NOT NULL DEFAULT 1, 
    [Tier1Columns] NVARCHAR(MAX) NULL, 
    [Tier1ColumnOrder] NVARCHAR(MAX) NULL, 
    [Tier1SortOrder] NVARCHAR(1000) NULL, 
    [Tier1RollupGroup] NVARCHAR(50) NULL, 	
    [Tier2Columns] NVARCHAR(1000) NULL, 
    [Tier2ColumnOrder] NVARCHAR(MAX) NULL, 
    [Tier2SortOrder] NVARCHAR(1000) NULL, 
    [Tier2RollupGroup] NVARCHAR(50) NULL, 	
    [Tier3Columns] NVARCHAR(1000) NULL, 
    [Tier3ColumnOrder] NVARCHAR(MAX) NULL, 
    [Tier3SortOrder] NVARCHAR(1000) NULL, 
	[SORT_ORDER] [int] NOT NULL,
	[Archive] [bit] NULL,
	[CREATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[CREATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[UPDATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[UPDATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
    PRIMARY KEY CLUSTERED 
(
	[GridViewID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_GridView_Unique] UNIQUE NONCLUSTERED 
(
	[GridNameID] ASC,
	[WTS_RESOURCEID] ASC,
	[ViewName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
    CONSTRAINT [FK_GridView_WTS_RESOURCE] FOREIGN KEY ([WTS_RESOURCEID]) REFERENCES [WTS_RESOURCE]([WTS_RESOURCEID])
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[GridView] ADD  DEFAULT ((99)) FOR [SORT_ORDER]
GO

ALTER TABLE [dbo].[GridView] ADD  DEFAULT ((0)) FOR [Archive]
GO

ALTER TABLE [dbo].[GridView]  WITH CHECK ADD  CONSTRAINT [FK_GridView_GridName] FOREIGN KEY([GridNameID])
REFERENCES [dbo].[GridName] ([GridNameID])
GO

ALTER TABLE [dbo].[GridView] CHECK CONSTRAINT [FK_GridView_GridName]
GO

