USE WTS
GO

ALTER TABLE [dbo].[ORGANIZATION_DEFAULTROLE] DROP CONSTRAINT [FK_ORGANIZATION_DEFAULTROLE_ORGANIZATION]
GO

/****** Object:  Table [dbo].[ORGANIZATION_DEFAULTROLE]    Script Date: 7/2/2015 1:46:41 PM ******/
DROP TABLE [dbo].[ORGANIZATION_DEFAULTROLE]
GO

/****** Object:  Table [dbo].[ORGANIZATION_DEFAULTROLE]    Script Date: 7/2/2015 1:46:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ORGANIZATION_DEFAULTROLE](
	[ORGANIZATION_DEFAULTROLEID] [int] IDENTITY(1,1) NOT NULL,
	[ORGANIZATIONID] [int] NOT NULL,
	[ROLENAME] [nvarchar](256) NOT NULL,
	[DESCRIPTION] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[ORGANIZATION_DEFAULTROLEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[ORGANIZATION_DEFAULTROLE]  WITH CHECK ADD  CONSTRAINT [FK_ORGANIZATION_DEFAULTROLE_ORGANIZATION] FOREIGN KEY([ORGANIZATIONID])
REFERENCES [dbo].[ORGANIZATION] ([ORGANIZATIONID])
GO

ALTER TABLE [dbo].[ORGANIZATION_DEFAULTROLE] CHECK CONSTRAINT [FK_ORGANIZATION_DEFAULTROLE_ORGANIZATION]
GO

