USE [WTS]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [FK_RQMTSystem_WTS_SYSTEM]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [FK_RQMTSystem_STATUS]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [FK_RQMTSystem_RQMTStatusID]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [FK_RQMTSystem_RQMTStageID]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [FK_RQMTSystem_RQMT]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [FK_RQMTSystem_CriticalityID]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [DF__RQMTSyste__RQMTA__5FF4C5A6]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [DF__RQMTSyste__Updat__294DD0DB]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [DF__RQMTSyste__Updat__2859ACA2]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [DF__RQMTSyste__Creat__27658869]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [DF__RQMTSyste__Creat__26716430]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [DF__RQMTSyste__Archi__257D3FF7]
GO

ALTER TABLE [dbo].[RQMTSystem] DROP CONSTRAINT [DF__RQMTSyste__Revis__24891BBE]
GO

/****** Object:  Table [dbo].[RQMTSystem]    Script Date: 6/13/2018 3:32:12 PM ******/
DROP TABLE [dbo].[RQMTSystem]
GO

/****** Object:  Table [dbo].[RQMTSystem]    Script Date: 6/13/2018 3:32:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RQMTSystem](
	[RQMTSystemID] [int] IDENTITY(1,1) NOT NULL,
	[RQMTID] [int] NOT NULL,
	[WTS_SYSTEMID] [int] NOT NULL,
	[Revision] [int] NOT NULL,
	[RevisionStatusID] [int] NULL,
	[Archive] [bit] NOT NULL,
	[CreatedBy] [nvarchar](255) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[UpdatedBy] [nvarchar](255) NOT NULL,
	[UpdatedDate] [datetime] NOT NULL,
	[RQMTStageID] [int] NULL,
	[CriticalityID] [int] NULL,
	[RQMTAccepted] [bit] NOT NULL,
	[RQMTStatusID] [int] NULL,
	[RQMTAccepted_By] [nvarchar](255) NULL,
	[RQMTAccepted_Date] [datetime] NULL,
 CONSTRAINT [PK_RQMTSystem] PRIMARY KEY CLUSTERED 
(
	[RQMTSystemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RQMTSystem] ADD  DEFAULT ((0)) FOR [Revision]
GO

ALTER TABLE [dbo].[RQMTSystem] ADD  DEFAULT ((0)) FOR [Archive]
GO

ALTER TABLE [dbo].[RQMTSystem] ADD  DEFAULT ('WTS') FOR [CreatedBy]
GO

ALTER TABLE [dbo].[RQMTSystem] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO

ALTER TABLE [dbo].[RQMTSystem] ADD  DEFAULT ('WTS') FOR [UpdatedBy]
GO

ALTER TABLE [dbo].[RQMTSystem] ADD  DEFAULT (getdate()) FOR [UpdatedDate]
GO

ALTER TABLE [dbo].[RQMTSystem] ADD  DEFAULT ((0)) FOR [RQMTAccepted]
GO

ALTER TABLE [dbo].[RQMTSystem]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSystem_CriticalityID] FOREIGN KEY([CriticalityID])
REFERENCES [dbo].[RQMTAttribute] ([RQMTAttributeID])
GO

ALTER TABLE [dbo].[RQMTSystem] CHECK CONSTRAINT [FK_RQMTSystem_CriticalityID]
GO

ALTER TABLE [dbo].[RQMTSystem]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSystem_RQMT] FOREIGN KEY([RQMTID])
REFERENCES [dbo].[RQMT] ([RQMTID])
GO

ALTER TABLE [dbo].[RQMTSystem] CHECK CONSTRAINT [FK_RQMTSystem_RQMT]
GO

ALTER TABLE [dbo].[RQMTSystem]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSystem_RQMTStageID] FOREIGN KEY([RQMTStageID])
REFERENCES [dbo].[RQMTAttribute] ([RQMTAttributeID])
GO

ALTER TABLE [dbo].[RQMTSystem] CHECK CONSTRAINT [FK_RQMTSystem_RQMTStageID]
GO

ALTER TABLE [dbo].[RQMTSystem]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSystem_RQMTStatusID] FOREIGN KEY([RQMTStatusID])
REFERENCES [dbo].[RQMTAttribute] ([RQMTAttributeID])
GO

ALTER TABLE [dbo].[RQMTSystem] CHECK CONSTRAINT [FK_RQMTSystem_RQMTStatusID]
GO

ALTER TABLE [dbo].[RQMTSystem]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSystem_STATUS] FOREIGN KEY([RevisionStatusID])
REFERENCES [dbo].[STATUS] ([STATUSID])
GO

ALTER TABLE [dbo].[RQMTSystem] CHECK CONSTRAINT [FK_RQMTSystem_STATUS]
GO

ALTER TABLE [dbo].[RQMTSystem]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSystem_WTS_SYSTEM] FOREIGN KEY([WTS_SYSTEMID])
REFERENCES [dbo].[WTS_SYSTEM] ([WTS_SYSTEMID])
GO

ALTER TABLE [dbo].[RQMTSystem] CHECK CONSTRAINT [FK_RQMTSystem_WTS_SYSTEM]
GO

