USE [WTS]
GO

/****** Object:  Index [IDX_RQMTSetName]    Script Date: 5/11/2018 4:08:10 PM ******/
DROP INDEX [IDX_RQMTSetName] ON [dbo].[RQMTSetName]
GO

/****** Object:  Table [dbo].[RQMTSetName]    Script Date: 5/11/2018 4:08:10 PM ******/
DROP TABLE [dbo].[RQMTSetName]
GO

/****** Object:  Table [dbo].[RQMTSetName]    Script Date: 5/11/2018 4:08:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RQMTSetName](
	[RQMTSetNameID] [int] IDENTITY(1,1) NOT NULL,
	[RQMTSetName] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RQMTSetNameID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IDX_RQMTSetName]    Script Date: 5/11/2018 4:08:10 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IDX_RQMTSetName] ON [dbo].[RQMTSetName]
(
	[RQMTSetName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


