USE [WTS]
GO

ALTER TABLE [dbo].[RQMTSystemDefectSR] DROP CONSTRAINT [FK_RQMTSystemDefectSR_SR]
GO

ALTER TABLE [dbo].[RQMTSystemDefectSR] DROP CONSTRAINT [FK_RQMTSystemDefectSR_AORSR]
GO

/****** Object:  Index [IDX_RQMTSystemDefectSR_SR]    Script Date: 9/11/2018 3:13:52 PM ******/
DROP INDEX [IDX_RQMTSystemDefectSR_SR] ON [dbo].[RQMTSystemDefectSR]
GO

/****** Object:  Index [IDX_RQMTSystemDefectSR_Defect]    Script Date: 9/11/2018 3:13:52 PM ******/
DROP INDEX [IDX_RQMTSystemDefectSR_Defect] ON [dbo].[RQMTSystemDefectSR]
GO

/****** Object:  Index [IDX_RQMTSystemDefectSR_AORSR]    Script Date: 9/11/2018 3:13:52 PM ******/
DROP INDEX [IDX_RQMTSystemDefectSR_AORSR] ON [dbo].[RQMTSystemDefectSR]
GO

/****** Object:  Table [dbo].[RQMTSystemDefectSR]    Script Date: 9/11/2018 3:13:52 PM ******/
DROP TABLE [dbo].[RQMTSystemDefectSR]
GO

/****** Object:  Table [dbo].[RQMTSystemDefectSR]    Script Date: 9/11/2018 3:13:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RQMTSystemDefectSR](
	[RQMTSystemDefectSRID] [int] IDENTITY(1,1) NOT NULL,
	[RQMTSystemDefectID] [int] NOT NULL,
	[SRID] [int] NULL,
	[AORSR_SRID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[RQMTSystemDefectSRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Index [IDX_RQMTSystemDefectSR_AORSR]    Script Date: 9/11/2018 3:13:52 PM ******/
CREATE NONCLUSTERED INDEX [IDX_RQMTSystemDefectSR_AORSR] ON [dbo].[RQMTSystemDefectSR]
(
	[AORSR_SRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IDX_RQMTSystemDefectSR_Defect]    Script Date: 9/11/2018 3:13:52 PM ******/
CREATE NONCLUSTERED INDEX [IDX_RQMTSystemDefectSR_Defect] ON [dbo].[RQMTSystemDefectSR]
(
	[RQMTSystemDefectID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IDX_RQMTSystemDefectSR_SR]    Script Date: 9/11/2018 3:13:52 PM ******/
CREATE NONCLUSTERED INDEX [IDX_RQMTSystemDefectSR_SR] ON [dbo].[RQMTSystemDefectSR]
(
	[SRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RQMTSystemDefectSR]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSystemDefectSR_AORSR] FOREIGN KEY([AORSR_SRID])
REFERENCES [dbo].[AORSR] ([SRID])
GO

ALTER TABLE [dbo].[RQMTSystemDefectSR] CHECK CONSTRAINT [FK_RQMTSystemDefectSR_AORSR]
GO

ALTER TABLE [dbo].[RQMTSystemDefectSR]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSystemDefectSR_SR] FOREIGN KEY([SRID])
REFERENCES [dbo].[SR] ([SRID])
GO

ALTER TABLE [dbo].[RQMTSystemDefectSR] CHECK CONSTRAINT [FK_RQMTSystemDefectSR_SR]
GO


