USE [WTS]
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem] DROP CONSTRAINT [FK_RQMTSet_RQMTSystem_RQMTSystem]
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem] DROP CONSTRAINT [FK_RQMTSet_RQMTSystem_RQMTSet]
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem] DROP CONSTRAINT [FK_RQMTSet_RQMTSystem_PRIORITYID]
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem] DROP CONSTRAINT [FK_RQMTSet_RQMTSystem_Parent]
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem] DROP CONSTRAINT [DF_RQMTSet_RQMTSystem_OutlineIndex]
GO

/****** Object:  Index [IDX_RQMTSet_RQMTSystem_RQMTSystem]    Script Date: 5/11/2018 4:07:56 PM ******/
DROP INDEX [IDX_RQMTSet_RQMTSystem_RQMTSystem] ON [dbo].[RQMTSet_RQMTSystem]
GO

/****** Object:  Index [IDX_RQMTSet_RQMTSystem_RQMTSet]    Script Date: 5/11/2018 4:07:56 PM ******/
DROP INDEX [IDX_RQMTSet_RQMTSystem_RQMTSet] ON [dbo].[RQMTSet_RQMTSystem]
GO

/****** Object:  Index [IDX_RQMTSet_RQMTSystem]    Script Date: 5/11/2018 4:07:56 PM ******/
DROP INDEX [IDX_RQMTSet_RQMTSystem] ON [dbo].[RQMTSet_RQMTSystem]
GO

/****** Object:  Table [dbo].[RQMTSet_RQMTSystem]    Script Date: 5/11/2018 4:07:56 PM ******/
DROP TABLE [dbo].[RQMTSet_RQMTSystem]
GO

/****** Object:  Table [dbo].[RQMTSet_RQMTSystem]    Script Date: 5/11/2018 4:07:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RQMTSet_RQMTSystem](
	[RQMTSet_RQMTSystemID] [int] IDENTITY(1,1) NOT NULL,
	[RQMTSetID] [int] NOT NULL,
	[RQMTSystemID] [int] NOT NULL,
	[ParentRQMTSet_RQMTSystemID] [int] NULL,
	[OutlineIndex] [int] NOT NULL,
	[PRIORITYID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[RQMTSet_RQMTSystemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Index [IDX_RQMTSet_RQMTSystem]    Script Date: 5/11/2018 4:07:56 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IDX_RQMTSet_RQMTSystem] ON [dbo].[RQMTSet_RQMTSystem]
(
	[RQMTSetID] ASC,
	[RQMTSystemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IDX_RQMTSet_RQMTSystem_RQMTSet]    Script Date: 5/11/2018 4:07:56 PM ******/
CREATE NONCLUSTERED INDEX [IDX_RQMTSet_RQMTSystem_RQMTSet] ON [dbo].[RQMTSet_RQMTSystem]
(
	[RQMTSetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IDX_RQMTSet_RQMTSystem_RQMTSystem]    Script Date: 5/11/2018 4:07:56 PM ******/
CREATE NONCLUSTERED INDEX [IDX_RQMTSet_RQMTSystem_RQMTSystem] ON [dbo].[RQMTSet_RQMTSystem]
(
	[RQMTSystemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem] ADD  CONSTRAINT [DF_RQMTSet_RQMTSystem_OutlineIndex]  DEFAULT ((0)) FOR [OutlineIndex]
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSet_RQMTSystem_Parent] FOREIGN KEY([RQMTSet_RQMTSystemID])
REFERENCES [dbo].[RQMTSet_RQMTSystem] ([RQMTSet_RQMTSystemID])
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem] CHECK CONSTRAINT [FK_RQMTSet_RQMTSystem_Parent]
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSet_RQMTSystem_PRIORITYID] FOREIGN KEY([PRIORITYID])
REFERENCES [dbo].[PRIORITY] ([PRIORITYID])
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem] CHECK CONSTRAINT [FK_RQMTSet_RQMTSystem_PRIORITYID]
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSet_RQMTSystem_RQMTSet] FOREIGN KEY([RQMTSetID])
REFERENCES [dbo].[RQMTSet] ([RQMTSetID])
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem] CHECK CONSTRAINT [FK_RQMTSet_RQMTSystem_RQMTSet]
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem]  WITH CHECK ADD  CONSTRAINT [FK_RQMTSet_RQMTSystem_RQMTSystem] FOREIGN KEY([RQMTSystemID])
REFERENCES [dbo].[RQMTSystem] ([RQMTSystemID])
GO

ALTER TABLE [dbo].[RQMTSet_RQMTSystem] CHECK CONSTRAINT [FK_RQMTSet_RQMTSystem_RQMTSystem]
GO


