USE WTS
GO

/****** Object:  Table [dbo].[WORKITEMTYPE]    Script Date: 7/2/2015 1:53:09 PM ******/
DROP TABLE [dbo].[WORKITEMTYPE]
GO

/****** Object:  Table [dbo].[WORKITEMTYPE]    Script Date: 7/2/2015 1:53:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WORKITEMTYPE](
	[WORKITEMTYPEID] [int] IDENTITY(1,1) NOT NULL,
	[WORKITEMTYPE] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NULL,
	[PDDTDR_PHASEID] [int] NULL,
	[WorkloadAllocationID] [int] NULL,
	[SORT_ORDER] [int] NULL DEFAULT ((99)),
	[ARCHIVE] [bit] NOT NULL DEFAULT ((0)),
	[CREATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[CREATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[UPDATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[UPDATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED
(
	[WORKITEMTYPEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WORKITEMTYPE]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEMTYPE_PDDTDR_PHASEID] FOREIGN KEY([PDDTDR_PHASEID])
REFERENCES [dbo].[PDDTDR_PHASE] ([PDDTDR_PHASEID])
GO

ALTER TABLE [dbo].[WORKITEMTYPE]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEMTYPE_WorkloadAllocationID] FOREIGN KEY([WorkloadAllocationID])
REFERENCES [dbo].[WorkloadAllocation] ([WorkloadAllocationID])
GO