USE WTS
GO

ALTER TABLE [dbo].[WORKITEM_TASK_HISTORY] DROP CONSTRAINT [FK_WORKITEM_TASK_HISTORY_ITEM_UPDATETYPE]
GO

/****** Object:  Table [dbo].[WORKITEM_TASK_HISTORY]    Script Date: 10/2/2015 12:00:00 PM ******/
DROP TABLE [dbo].[WORKITEM_TASK_HISTORY]
GO

/****** Object:  Table [dbo].[WORKITEM_TASK_HISTORY]    Script Date: 10/2/2015 12:00:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[WORKITEM_TASK_HISTORY](
	[WORKITEM_TASK_HISTORYID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_UPDATETYPEID] [int] NOT NULL,
	[WORKITEM_TASKID] [int] NOT NULL,
	[FieldChanged] [nvarchar](50) NOT NULL,
	[OldValue] [varchar](max) NULL,
	[NewValue] [varchar](max) NULL,
	[CREATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[CREATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[UPDATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[UPDATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[WORKITEM_TASK_HISTORYID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[WORKITEM_TASK_HISTORY]  WITH CHECK ADD CONSTRAINT [FK_WORKITEM_TASK_HISTORY_ITEM_UPDATETYPE] FOREIGN KEY([ITEM_UPDATETYPEID])
REFERENCES [dbo].[ITEM_UPDATETYPE] ([ITEM_UPDATETYPEID])
GO

ALTER TABLE [dbo].[WORKITEM_TASK_HISTORY] CHECK CONSTRAINT [FK_WORKITEM_TASK_HISTORY_ITEM_UPDATETYPE]
GO

