USE WTS
GO

ALTER TABLE [dbo].[WORKREQUEST_COMMENT] DROP CONSTRAINT [FK_WORKREQUEST_COMMENT_WORKREQUEST]
GO

ALTER TABLE [dbo].[WORKREQUEST_COMMENT] DROP CONSTRAINT [FK_WORKREQUEST_COMMENT_COMMENT]
GO

ALTER TABLE [dbo].[WORKREQUEST_COMMENT] DROP CONSTRAINT [DF__WORKREQUE__UPDAT__53C2623D]
GO

ALTER TABLE [dbo].[WORKREQUEST_COMMENT] DROP CONSTRAINT [DF__WORKREQUE__UPDAT__52CE3E04]
GO

ALTER TABLE [dbo].[WORKREQUEST_COMMENT] DROP CONSTRAINT [DF__WORKREQUE__CREAT__51DA19CB]
GO

ALTER TABLE [dbo].[WORKREQUEST_COMMENT] DROP CONSTRAINT [DF__WORKREQUE__CREAT__50E5F592]
GO

ALTER TABLE [dbo].[WORKREQUEST_COMMENT] DROP CONSTRAINT [DF__WORKREQUE__ARCHI__4FF1D159]
GO

/****** Object:  Table [dbo].[WORKREQUEST_COMMENT]    Script Date: 7/2/2015 2:01:24 PM ******/
DROP TABLE [dbo].[WORKREQUEST_COMMENT]
GO

/****** Object:  Table [dbo].[WORKREQUEST_COMMENT]    Script Date: 7/2/2015 2:01:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WORKREQUEST_COMMENT](
	[WORKREQUEST_COMMENTID] [int] IDENTITY(1,1) NOT NULL,
	[WORKREQUESTID] [int] NOT NULL,
	[COMMENTID] [int] NOT NULL,
	[ARCHIVE] [bit] NOT NULL DEFAULT ((0)),
	[CREATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[CREATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[UPDATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[UPDATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_WORKREQUEST_COMMENT] PRIMARY KEY CLUSTERED 
(
	[WORKREQUEST_COMMENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WORKREQUEST_COMMENT]  WITH CHECK ADD  CONSTRAINT [FK_WORKREQUEST_COMMENT_COMMENT] FOREIGN KEY([COMMENTID])
REFERENCES [dbo].[COMMENT] ([COMMENTID])
GO

ALTER TABLE [dbo].[WORKREQUEST_COMMENT] CHECK CONSTRAINT [FK_WORKREQUEST_COMMENT_COMMENT]
GO

ALTER TABLE [dbo].[WORKREQUEST_COMMENT]  WITH CHECK ADD  CONSTRAINT [FK_WORKREQUEST_COMMENT_WORKREQUEST] FOREIGN KEY([WORKREQUESTID])
REFERENCES [dbo].[WORKREQUEST] ([WORKREQUESTID])
GO

ALTER TABLE [dbo].[WORKREQUEST_COMMENT] CHECK CONSTRAINT [FK_WORKREQUEST_COMMENT_WORKREQUEST]
GO

