USE WTS
GO

ALTER TABLE [dbo].[WORKITEM_SR] DROP CONSTRAINT [FK_WORKITEM_SR_WORKITEM]
GO

ALTER TABLE [dbo].[WORKITEM_SR] DROP CONSTRAINT [FK_WORKITEM_SR_SUSTAINMENTREQUEST]
GO

ALTER TABLE [dbo].[WORKITEM_SR] DROP CONSTRAINT [DF__WORKITEM___UPDAT__7A8729A3]
GO

ALTER TABLE [dbo].[WORKITEM_SR] DROP CONSTRAINT [DF__WORKITEM___UPDAT__7993056A]
GO

ALTER TABLE [dbo].[WORKITEM_SR] DROP CONSTRAINT [DF__WORKITEM___CREAT__789EE131]
GO

ALTER TABLE [dbo].[WORKITEM_SR] DROP CONSTRAINT [DF__WORKITEM___CREAT__77AABCF8]
GO

ALTER TABLE [dbo].[WORKITEM_SR] DROP CONSTRAINT [DF__WORKITEM___ARCHI__76B698BF]
GO

/****** Object:  Table [dbo].[WORKITEM_SR]    Script Date: 7/2/2015 1:54:30 PM ******/
DROP TABLE [dbo].[WORKITEM_SR]
GO

/****** Object:  Table [dbo].[WORKITEM_SR]    Script Date: 7/2/2015 1:54:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WORKITEM_SR](
	[WORKITEM_SRID] [int] IDENTITY(1,1) NOT NULL,
	[WORKITEMID] [int] NOT NULL,
	[SUSTAINMENTREQUESTID] [int] NOT NULL,
	[ARCHIVE] [bit] NOT NULL DEFAULT ((0)),
	[CREATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[CREATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[UPDATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[UPDATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[WORKITEM_SRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WORKITEM_SR]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_SR_SUSTAINMENTREQUEST] FOREIGN KEY([SUSTAINMENTREQUESTID])
REFERENCES [dbo].[SUSTAINMENTREQUEST] ([SUSTAINMENTREQUESTID])
GO

ALTER TABLE [dbo].[WORKITEM_SR] CHECK CONSTRAINT [FK_WORKITEM_SR_SUSTAINMENTREQUEST]
GO

ALTER TABLE [dbo].[WORKITEM_SR]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_SR_WORKITEM] FOREIGN KEY([WORKITEMID])
REFERENCES [dbo].[WORKITEM] ([WORKITEMID])
GO

ALTER TABLE [dbo].[WORKITEM_SR] CHECK CONSTRAINT [FK_WORKITEM_SR_WORKITEM]
GO

