USE WTS
GO

ALTER TABLE [dbo].[WORKREQUEST] DROP CONSTRAINT [FK_WORKREQUEST_WTS_SCOPE]
GO

ALTER TABLE [dbo].[WORKREQUEST] DROP CONSTRAINT [FK_WORKREQUEST_SUBMITTEDBY]
GO

ALTER TABLE [dbo].[WORKREQUEST] DROP CONSTRAINT [FK_WORKREQUEST_SME]
GO

ALTER TABLE [dbo].[WORKREQUEST] DROP CONSTRAINT [FK_WORKREQUEST_REQUESTTYPE]
GO

ALTER TABLE [dbo].[WORKREQUEST] DROP CONSTRAINT [FK_WORKREQUEST_PRIORITY]
GO

ALTER TABLE [dbo].[WORKREQUEST] DROP CONSTRAINT [FK_WORKREQUEST_ORGANIZATION]
GO

ALTER TABLE [dbo].[WORKREQUEST] DROP CONSTRAINT [FK_WORKREQUEST_LEAD_RESOURCE]
GO

ALTER TABLE [dbo].[WORKREQUEST] DROP CONSTRAINT [FK_WORKREQUEST_LEAD_IA_TW]
GO

ALTER TABLE [dbo].[WORKREQUEST] DROP CONSTRAINT [FK_WORKREQUEST_EFFORT]
GO

ALTER TABLE [dbo].[WORKREQUEST] DROP CONSTRAINT [FK_WORKREQUEST_CONTRACT]
GO

/****** Object:  Table [dbo].[WORKREQUEST]    Script Date: 7/2/2015 1:52:19 PM ******/
DROP TABLE [dbo].[WORKREQUEST]
GO

/****** Object:  Table [dbo].[WORKREQUEST]    Script Date: 7/2/2015 1:52:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WORKREQUEST](
	[WORKREQUESTID] [int] IDENTITY(1,1) NOT NULL,
	[REQUESTTYPEID] [int] NOT NULL,
	[RequestGroupID] INT NULL,
	[CONTRACTID] [int] NULL,
	[ORGANIZATIONID] [int] NULL,
	[WTS_SCOPEID] [int] NULL,
	[EFFORTID] [int] NULL,
	[PROGRESSID] [int] NULL,
	[SMEID] [int] NULL,
	[LEAD_IA_TWID] [int] NULL,
	[LEAD_RESOURCEID] [int] NULL,
	[OP_PRIORITYID] [int] NULL,
	[TD_STATUSID] [int] NULL,
	[CD_STATUSID] [int] NULL,
	[C_STATUSID] [int] NULL,
	[IT_STATUSID] [int] NULL,
	[CVT_STATUSID] [int] NULL,
	[A_STATUSID] [int] NULL,
	[CR_STATUSID] [int] NULL,
	[TITLE] [nvarchar](150) NOT NULL,
	[DESCRIPTION] [nvarchar](500) NULL,
	[JUSTIFICATION] [nvarchar](500) NULL,
	[ARCHIVE] [bit] NOT NULL DEFAULT ((0)),
	[CREATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[CREATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[UPDATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[UPDATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[SUBMITTEDBY] [int] NULL, 
    PRIMARY KEY CLUSTERED 
(
	[WORKREQUESTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
    CONSTRAINT [FK_WORKREQUEST_RequestGroup] FOREIGN KEY ([RequestGroupID]) REFERENCES [RequestGroup]([RequestGroupID]), 
    CONSTRAINT [FK_WORKREQUEST_STATUS_TD] FOREIGN KEY ([TD_STATUSID]) REFERENCES [STATUS]([STATUSID]), 
    CONSTRAINT [FK_WORKREQUEST_STATUS_CD] FOREIGN KEY ([CD_STATUSID]) REFERENCES [STATUS]([STATUSID]), 
    CONSTRAINT [FK_WORKREQUEST_STATUS_C] FOREIGN KEY ([C_STATUSID]) REFERENCES [STATUS]([STATUSID]), 
    CONSTRAINT [FK_WORKREQUEST_STATUS_IT] FOREIGN KEY ([IT_STATUSID]) REFERENCES [STATUS]([STATUSID]), 
    CONSTRAINT [FK_WORKREQUEST_STATUS_CVT] FOREIGN KEY ([CVT_STATUSID]) REFERENCES [STATUS]([STATUSID]), 
    CONSTRAINT [FK_WORKREQUEST_STATUS_A] FOREIGN KEY ([A_STATUSID]) REFERENCES [STATUS]([STATUSID]), 
    CONSTRAINT [FK_WORKREQUEST_STATUS_CR] FOREIGN KEY ([CR_STATUSID]) REFERENCES [STATUS]([STATUSID])
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WORKREQUEST]  WITH CHECK ADD  CONSTRAINT [FK_WORKREQUEST_CONTRACT] FOREIGN KEY([CONTRACTID])
REFERENCES [dbo].[CONTRACT] ([CONTRACTID])
GO

ALTER TABLE [dbo].[WORKREQUEST] CHECK CONSTRAINT [FK_WORKREQUEST_CONTRACT]
GO

ALTER TABLE [dbo].[WORKREQUEST]  WITH CHECK ADD  CONSTRAINT [FK_WORKREQUEST_EFFORT] FOREIGN KEY([EFFORTID])
REFERENCES [dbo].[EFFORT] ([EFFORTID])
GO

ALTER TABLE [dbo].[WORKREQUEST] CHECK CONSTRAINT [FK_WORKREQUEST_EFFORT]
GO

ALTER TABLE [dbo].[WORKREQUEST]  WITH CHECK ADD  CONSTRAINT [FK_WORKREQUEST_LEAD_IA_TW] FOREIGN KEY([LEAD_IA_TWID])
REFERENCES [dbo].[WTS_RESOURCE] ([WTS_RESOURCEID])
GO

ALTER TABLE [dbo].[WORKREQUEST] CHECK CONSTRAINT [FK_WORKREQUEST_LEAD_IA_TW]
GO

ALTER TABLE [dbo].[WORKREQUEST]  WITH CHECK ADD  CONSTRAINT [FK_WORKREQUEST_LEAD_RESOURCE] FOREIGN KEY([LEAD_RESOURCEID])
REFERENCES [dbo].[WTS_RESOURCE] ([WTS_RESOURCEID])
GO

ALTER TABLE [dbo].[WORKREQUEST] CHECK CONSTRAINT [FK_WORKREQUEST_LEAD_RESOURCE]
GO

ALTER TABLE [dbo].[WORKREQUEST]  WITH CHECK ADD  CONSTRAINT [FK_WORKREQUEST_ORGANIZATION] FOREIGN KEY([ORGANIZATIONID])
REFERENCES [dbo].[ORGANIZATION] ([ORGANIZATIONID])
GO

ALTER TABLE [dbo].[WORKREQUEST] CHECK CONSTRAINT [FK_WORKREQUEST_ORGANIZATION]
GO
ALTER TABLE [dbo].[WORKREQUEST]  WITH CHECK ADD  CONSTRAINT [FK_WORKREQUEST_PRIORITY] FOREIGN KEY([OP_PRIORITYID])
REFERENCES [dbo].[PRIORITY] ([PRIORITYID])
GO

ALTER TABLE [dbo].[WORKREQUEST] CHECK CONSTRAINT [FK_WORKREQUEST_PRIORITY]
GO

ALTER TABLE [dbo].[WORKREQUEST]  WITH CHECK ADD  CONSTRAINT [FK_WORKREQUEST_REQUESTTYPE] FOREIGN KEY([REQUESTTYPEID])
REFERENCES [dbo].[REQUESTTYPE] ([REQUESTTYPEID])
GO

ALTER TABLE [dbo].[WORKREQUEST] CHECK CONSTRAINT [FK_WORKREQUEST_REQUESTTYPE]
GO

ALTER TABLE [dbo].[WORKREQUEST]  WITH CHECK ADD  CONSTRAINT [FK_WORKREQUEST_SME] FOREIGN KEY([SMEID])
REFERENCES [dbo].[WTS_RESOURCE] ([WTS_RESOURCEID])
GO

ALTER TABLE [dbo].[WORKREQUEST] CHECK CONSTRAINT [FK_WORKREQUEST_SME]
GO

ALTER TABLE [dbo].[WORKREQUEST]  WITH CHECK ADD  CONSTRAINT [FK_WORKREQUEST_SUBMITTEDBY] FOREIGN KEY([SUBMITTEDBY])
REFERENCES [dbo].[WTS_RESOURCE] ([WTS_RESOURCEID])
GO

ALTER TABLE [dbo].[WORKREQUEST] CHECK CONSTRAINT [FK_WORKREQUEST_SUBMITTEDBY]
GO

ALTER TABLE [dbo].[WORKREQUEST]  WITH CHECK ADD  CONSTRAINT [FK_WORKREQUEST_WTS_SCOPE] FOREIGN KEY([WTS_SCOPEID])
REFERENCES [dbo].[WTS_SCOPE] ([WTS_SCOPEID])
GO

ALTER TABLE [dbo].[WORKREQUEST] CHECK CONSTRAINT [FK_WORKREQUEST_WTS_SCOPE]
GO

