USE WTS
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WORKITEM_ALLOCATION]') AND parent_object_id = OBJECT_ID(N'[dbo].[WORKITEM]'))
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [FK_WORKITEM_ALLOCATION]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WORKITEM_ASSIGNEDRESOURCE]') AND parent_object_id = OBJECT_ID(N'[dbo].[WORKITEM]'))
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [FK_WORKITEM_ASSIGNEDRESOURCE]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WORKITEM_PRIMARYRESOURCE]') AND parent_object_id = OBJECT_ID(N'[dbo].[WORKITEM]'))
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [FK_WORKITEM_PRIMARYRESOURCE]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WORKITEM_PRIORITY]') AND parent_object_id = OBJECT_ID(N'[dbo].[WORKITEM]'))
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [FK_WORKITEM_PRIORITY]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WORKITEM_SECONDARYRESOURCE]') AND parent_object_id = OBJECT_ID(N'[dbo].[WORKITEM]'))
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [FK_WORKITEM_SECONDARYRESOURCE]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WORKITEM_STATUS]') AND parent_object_id = OBJECT_ID(N'[dbo].[WORKITEM]'))
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [FK_WORKITEM_STATUS]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WORKITEM_WORKITEMTYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[WORKITEM]'))
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [FK_WORKITEM_WORKITEMTYPE]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WORKITEM_WORKREQUEST]') AND parent_object_id = OBJECT_ID(N'[dbo].[WORKITEM]'))
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [FK_WORKITEM_WORKREQUEST]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_WORKITEM_WTS_SYSTEM]') AND parent_object_id = OBJECT_ID(N'[dbo].[WORKITEM]'))
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [FK_WORKITEM_WTS_SYSTEM]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__WORKITEM__COMPLE__13BCEBC1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [DF__WORKITEM__COMPLE__13BCEBC1]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__WORKITEM__ARCHIV__14B10FFA]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [DF__WORKITEM__ARCHIV__14B10FFA]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__WORKITEM__CREATE__15A53433]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [DF__WORKITEM__CREATE__15A53433]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__WORKITEM__CREATE__1699586C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [DF__WORKITEM__CREATE__1699586C]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__WORKITEM__UPDATE__178D7CA5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [DF__WORKITEM__UPDATE__178D7CA5]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__WORKITEM__UPDATE__1881A0DE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [DF__WORKITEM__UPDATE__1881A0DE]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__WORKITEM__Reprod__1975C517]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [DF__WORKITEM__Reprod__1975C517]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__WORKITEM__Reprod__1A69E950]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [DF__WORKITEM__Reprod__1A69E950]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__WORKITEM__Deploy__1B5E0D89]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [DF__WORKITEM__Deploy__1B5E0D89]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__WORKITEM__Deploy__1C5231C2]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [DF__WORKITEM__Deploy__1C5231C2]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__WORKITEM__Deploy__1D4655FB]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [DF__WORKITEM__Deploy__1D4655FB]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__WORKITEM__CVTSta__1E3A7A34]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[WORKITEM] DROP CONSTRAINT [DF__WORKITEM__CVTSta__1E3A7A34]
END

GO

USE [WTS]
GO

/****** Object:  Table [dbo].[WORKITEM]    Script Date: 07/13/2015 14:17:43 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[WORKITEM]') AND type in (N'U'))
DROP TABLE [dbo].[WORKITEM]
GO

USE [WTS]
GO

/****** Object:  Table [dbo].[WORKITEM]    Script Date: 07/13/2015 14:17:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WORKITEM](
	[WORKITEMID] [int] IDENTITY(1,1) NOT NULL,
	[WORKITEMTYPEID] [int] NOT NULL,
	[WTS_SYSTEMID] [int] NOT NULL,
	[PRIORITYID] [int] NOT NULL,
	[ALLOCATIONID] [int] NULL,
    [SubmittedByID] INT NULL, 
	[ASSIGNEDRESOURCEID] [int] NOT NULL,
	[PRIMARYRESOURCEID] [int] NULL,
	[SECONDARYRESOURCEID] [int] NULL,
	[PrimaryBusinessResourceID] INT NULL,
	[RESOURCEPRIORITYRANK] [int] NULL,
    [SecondaryResourceRank] INT NULL, 
    [PrimaryBusinessRank] INT NULL, 
	[STATUSID] [int] NOT NULL,
    [IVTRequired] BIT NULL DEFAULT 0, 
	[NEEDDATE] [date] NULL,
	[ESTIMATEDHOURS] [int] NULL,
	[EstimatedEffortID] INT NULL, 
    [ActualEffortID] INT NULL, 
	[ESTIMATEDCOMPLETIONDATE] [date] NULL,
	[COMPLETIONPERCENT] [int] NULL DEFAULT ((0)),
	[TITLE] [nvarchar](150) NOT NULL,
	[DESCRIPTION] [nvarchar](500) NULL,
	[WORKREQUESTID] [int] NULL,
	[BUGTRACKER_ID] [int] NULL,
	[ProductVersionID] [int] NULL,
	[MenuTypeID] [int] NULL,
	[MenuNameID] [int] NULL,
	[Production] [bit] NULL,
	[SR_Number] [int] NULL,
	[Reproduced_Biz] [bit] NULL DEFAULT ((0)),
	[Reproduced_Dev] [bit] NULL DEFAULT ((0)),
	[Deployed_Comm] [bit] NULL DEFAULT ((0)),
	[Deployed_Test] [bit] NULL DEFAULT ((0)),
	[Deployed_Prod] [bit] NULL DEFAULT ((0)),
	[DeployedBy_CommID] [int] NULL,
	[DeployedBy_TestID] [int] NULL,
	[DeployedBy_ProdID] [int] NULL,
	[DeployedDate_Comm] [datetime] NULL,
	[DeployedDate_Test] [datetime] NULL,
	[DeployedDate_Prod] [datetime] NULL,
	[PlannedDesignStart] [date] NULL,
	[PlannedDevStart] [date] NULL,
	[ActualDesignStart] [date] NULL,
	[ActualDevStart] [date] NULL,
	[ActualCompletionDate] [date] NULL,
	[CVTStep] [nvarchar](50) NULL,
	[CVTStatus] [nvarchar](25) NULL DEFAULT ('Not Ready'),
	[TesterID] [int] NULL,
	[WorkTypeID] [int] NULL,
	[WorkloadGroupID] INT NULL DEFAULT ((1)), 
	[WorkAreaID] INT NULL DEFAULT ((1)), 
	[ARCHIVE] [bit] NOT NULL DEFAULT ((0)),
	[CREATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[CREATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[UPDATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[UPDATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[PDDTDR_PHASEID INT NULL
    PRIMARY KEY CLUSTERED 
(
	[WORKITEMID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY], 
    CONSTRAINT [FK_WORKITEM_WorkloadGroup] FOREIGN KEY ([WorkloadGroupID]) REFERENCES [WorkloadGroup]([WorkloadGroupID]), 
    CONSTRAINT [FK_WORKITEM_WorkArea] FOREIGN KEY ([WorkAreaID]) REFERENCES [WorkArea]([WorkAreaID]), 
    CONSTRAINT [FK_WORKITEM_SUBMITTEDBY_RESOURCE] FOREIGN KEY ([SubmittedByID]) REFERENCES [WTS_RESOURCE]([WTS_RESOURCEID]), 
    CONSTRAINT [FK_WORKITEM_EstimatedEffort] FOREIGN KEY ([EstimatedEffortID]) REFERENCES [EffortSize]([EffortSizeID]), 
    CONSTRAINT [FK_WORKITEM_ActualEffort] FOREIGN KEY ([ActualEffortID]) REFERENCES [EffortSize]([EffortSizeID]), 
    CONSTRAINT [FK_WORKITEM_BusinessResource] FOREIGN KEY (PrimaryBusinessResourceID) REFERENCES [WTS_RESOURCE]([WTS_RESOURCEID])
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WORKITEM]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_ALLOCATION] FOREIGN KEY([ALLOCATIONID])
REFERENCES [dbo].[ALLOCATION] ([ALLOCATIONID])
GO

ALTER TABLE [dbo].[WORKITEM] CHECK CONSTRAINT [FK_WORKITEM_ALLOCATION]
GO

ALTER TABLE [dbo].[WORKITEM]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_ASSIGNEDRESOURCE] FOREIGN KEY([ASSIGNEDRESOURCEID])
REFERENCES [dbo].[WTS_RESOURCE] ([WTS_RESOURCEID])
GO

ALTER TABLE [dbo].[WORKITEM] CHECK CONSTRAINT [FK_WORKITEM_ASSIGNEDRESOURCE]
GO

ALTER TABLE [dbo].[WORKITEM]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_PRIMARYRESOURCE] FOREIGN KEY([PRIMARYRESOURCEID])
REFERENCES [dbo].[WTS_RESOURCE] ([WTS_RESOURCEID])
GO

ALTER TABLE [dbo].[WORKITEM] CHECK CONSTRAINT [FK_WORKITEM_PRIMARYRESOURCE]
GO

ALTER TABLE [dbo].[WORKITEM]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_PRIORITY] FOREIGN KEY([PRIORITYID])
REFERENCES [dbo].[PRIORITY] ([PRIORITYID])
GO

ALTER TABLE [dbo].[WORKITEM] CHECK CONSTRAINT [FK_WORKITEM_PRIORITY]
GO

ALTER TABLE [dbo].[WORKITEM]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_SECONDARYRESOURCE] FOREIGN KEY([SECONDARYRESOURCEID])
REFERENCES [dbo].[WTS_RESOURCE] ([WTS_RESOURCEID])
GO

ALTER TABLE [dbo].[WORKITEM] CHECK CONSTRAINT [FK_WORKITEM_SECONDARYRESOURCE]
GO

ALTER TABLE [dbo].[WORKITEM]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_STATUS] FOREIGN KEY([STATUSID])
REFERENCES [dbo].[STATUS] ([STATUSID])
GO

ALTER TABLE [dbo].[WORKITEM] CHECK CONSTRAINT [FK_WORKITEM_STATUS]
GO

ALTER TABLE [dbo].[WORKITEM]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_WORKITEMTYPE] FOREIGN KEY([WORKITEMTYPEID])
REFERENCES [dbo].[WORKITEMTYPE] ([WORKITEMTYPEID])
GO

ALTER TABLE [dbo].[WORKITEM] CHECK CONSTRAINT [FK_WORKITEM_WORKITEMTYPE]
GO

ALTER TABLE [dbo].[WORKITEM]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_WORKREQUEST] FOREIGN KEY([WORKREQUESTID])
REFERENCES [dbo].[WORKREQUEST] ([WORKREQUESTID])
GO

ALTER TABLE [dbo].[WORKITEM] CHECK CONSTRAINT [FK_WORKITEM_WORKREQUEST]
GO

ALTER TABLE [dbo].[WORKITEM]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_WTS_SYSTEM] FOREIGN KEY([WTS_SYSTEMID])
REFERENCES [dbo].[WTS_SYSTEM] ([WTS_SYSTEMID])
GO

ALTER TABLE [dbo].[WORKITEM] CHECK CONSTRAINT [FK_WORKITEM_WTS_SYSTEM]

ALTER TABLE WORKITEM WITH CHECK ADD CONSTRAINT [FK_WORKITEM_PDDTDR_PHASE] FOREIGN KEY ([PDDTDR_PHASEID]) 
REFERENCES [PDDTDR_PHASE]([PDDTDR_PHASEID])

ALTER TABLE [dbo].[WORKITEM] CHECK CONSTRAINT [FK_WORKITEM_PDDTDR_PHASE]
GO
