USE WTS
GO

ALTER TABLE [dbo].[WORKITEM_SUBSCRIBER] DROP CONSTRAINT [FK_WORKITEM_SUBSCRIBER_WTS_RESOURCE]
GO

ALTER TABLE [dbo].[WORKITEM_SUBSCRIBER] DROP CONSTRAINT [FK_WORKITEM_SUBSCRIBER_WORKITEM]
GO

ALTER TABLE [dbo].[WORKITEM_SUBSCRIBER] DROP CONSTRAINT [DF__WORKITEM___UPDAT__031C6FA4]
GO

ALTER TABLE [dbo].[WORKITEM_SUBSCRIBER] DROP CONSTRAINT [DF__WORKITEM___UPDAT__02284B6B]
GO

ALTER TABLE [dbo].[WORKITEM_SUBSCRIBER] DROP CONSTRAINT [DF__WORKITEM___CREAT__01342732]
GO

ALTER TABLE [dbo].[WORKITEM_SUBSCRIBER] DROP CONSTRAINT [DF__WORKITEM___CREAT__004002F9]
GO

ALTER TABLE [dbo].[WORKITEM_SUBSCRIBER] DROP CONSTRAINT [DF__WORKITEM___ARCHI__7F4BDEC0]
GO

/****** Object:  Table [dbo].[WORKITEM_SUBSCRIBER]    Script Date: 7/2/2015 1:54:46 PM ******/
DROP TABLE [dbo].[WORKITEM_SUBSCRIBER]
GO

/****** Object:  Table [dbo].[WORKITEM_SUBSCRIBER]    Script Date: 7/2/2015 1:54:46 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WORKITEM_SUBSCRIBER](
	[WORKITEM_SUBSCRIBERID] [int] IDENTITY(1,1) NOT NULL,
	[WORKITEMID] [int] NOT NULL,
	[WTS_RESOURCEID] [int] NOT NULL,
	[ARCHIVE] [bit] NOT NULL DEFAULT ((0)),
	[CREATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[CREATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
	[UPDATEDBY] [nvarchar](255) NOT NULL DEFAULT ('WTS_ADMIN'),
	[UPDATEDDATE] [datetime] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[WORKITEM_SUBSCRIBERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WORKITEM_SUBSCRIBER]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_SUBSCRIBER_WORKITEM] FOREIGN KEY([WORKITEMID])
REFERENCES [dbo].[WORKITEM] ([WORKITEMID])
GO

ALTER TABLE [dbo].[WORKITEM_SUBSCRIBER] CHECK CONSTRAINT [FK_WORKITEM_SUBSCRIBER_WORKITEM]
GO

ALTER TABLE [dbo].[WORKITEM_SUBSCRIBER]  WITH CHECK ADD  CONSTRAINT [FK_WORKITEM_SUBSCRIBER_WTS_RESOURCE] FOREIGN KEY([WTS_RESOURCEID])
REFERENCES [dbo].[WTS_RESOURCE] ([WTS_RESOURCEID])
GO

ALTER TABLE [dbo].[WORKITEM_SUBSCRIBER] CHECK CONSTRAINT [FK_WORKITEM_SUBSCRIBER_WTS_RESOURCE]
GO

