IF dbo.ColumnExists('dbo', 'RQMT', 'Universal') = 0
BEGIN
	ALTER TABLE RQMT ADD Universal BIT NOT NULL DEFAULT 0
END

IF dbo.TableExists('dbo', 'RQMTCategory') = 1
BEGIN
	DROP TABLE dbo.RQMTCategory
END

CREATE TABLE dbo.RQMTCategory
(
	RQMTCategoryID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	RQMTID INT NOT NULL,
	CategoryTypeID INT,
	ItemID INT
)

CREATE NONCLUSTERED INDEX [IDX_RQMTCategory_RQMT] ON [dbo].RQMTCategory(RQMTID ASC)

ALTER TABLE [dbo].RQMTCategory  WITH CHECK ADD CONSTRAINT [FK_RQMTCategory_RQMT] FOREIGN KEY(RQMTID) REFERENCES dbo.RQMT(RQMTID)